//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-kafka-client open source project
//
// Copyright (c) 2026 Apple Inc. and the swift-kafka-client project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-kafka-client project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

public struct KafkaProducerConfig: Sendable {
    // MARK: - Non-librdkafka configuration properties

    /// The time between two consecutive polls.
    /// Effectively controls the rate at which incoming events are consumed.
    /// Default: `.milliseconds(100)`
    public var pollInterval: Duration = .milliseconds(100)

    /// Maximum timeout for flushing outstanding produce requests when the ``KafkaProducer`` is shutting down.
    /// Default: `10000`
    public var shutdownFlushTimeoutMs: Int = 10000

    /// Producer metrics configuration.
    public var metrics: KafkaConfiguration.ProducerMetrics = .init()

    // MARK: - Properties generated from librdkafka config list

    /// Client identifier.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"client.id"`
    ///
    /// Default: rdkafka
    public var clientId: String?
    /// Initial list of brokers as a CSV list of broker host or host:port.
    /// The application may also use `rd_kafka_brokers_add()` to add brokers during runtime.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"metadata.broker.list"`
    public var metadataBrokerList: [String]?
    /// Alias for `metadata.broker.list`: Initial list of brokers as a CSV list of broker host or host:port.
    /// The application may also use `rd_kafka_brokers_add()` to add brokers during runtime.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"bootstrap.servers"`
    public var bootstrapServers: [String]?
    /// Maximum Kafka protocol request message size.
    /// Due to differing framing overhead between protocol versions the producer is unable to reliably enforce a strict max message limit at produce time and may exceed the maximum size by one message in protocol ProduceRequests, the broker will enforce the the topic's `max.message.bytes` limit (see Apache Kafka documentation).
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 1000000000
    ///
    /// librdkafka property name: `"message.max.bytes"`
    ///
    /// Default: 1000000
    public var messageMaxBytes: Int?
    /// Maximum size for message to be copied to buffer.
    /// Messages larger than this will be passed by reference (zero-copy) at the expense of larger iovecs.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"message.copy.max.bytes"`
    ///
    /// Default: 65535
    public var messageCopyMaxBytes: Int?
    /// Maximum Kafka protocol response message size.
    /// This serves as a safety precaution to avoid memory exhaustion in case of protocol hickups.
    /// This value must be at least `fetch.max.bytes`  + 512 to allow for protocol overhead; the value is adjusted automatically unless the configuration property is explicitly set.
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 2147483647
    ///
    /// librdkafka property name: `"receive.message.max.bytes"`
    ///
    /// Default: 100000000
    public var receiveMessageMaxBytes: Int?
    /// Maximum number of in-flight requests per broker connection.
    /// This is a generic property applied to all broker communication, however it is primarily relevant to produce requests.
    /// In particular, note that other mechanisms limit the number of outstanding consumer fetch request per broker to one.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 1000000
    ///
    /// librdkafka property name: `"max.in.flight.requests.per.connection"`
    ///
    /// Default: 1000000
    public var maxInFlightRequestsPerConnection: Int?
    /// Alias for `max.in.flight.requests.per.connection`: Maximum number of in-flight requests per broker connection.
    /// This is a generic property applied to all broker communication, however it is primarily relevant to produce requests.
    /// In particular, note that other mechanisms limit the number of outstanding consumer fetch request per broker to one.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 1000000
    ///
    /// librdkafka property name: `"max.in.flight"`
    ///
    /// Default: 1000000
    public var maxInFlight: Int?
    /// Period of time in milliseconds at which topic and broker metadata is refreshed in order to proactively discover any new brokers, topics, partitions or partition leader changes.
    /// Use -1 to disable the intervalled refresh (not recommended).
    /// If there are no locally referenced topics (no topic objects created, no messages produced, no subscription or no assignment) then only the broker list will be refreshed every interval but no more often than every 10s.
    ///
    /// Importance: low
    ///
    /// Value range: -1 .. 3600000
    ///
    /// librdkafka property name: `"topic.metadata.refresh.interval.ms"`
    ///
    /// Default: 300000
    public var topicMetadataRefreshIntervalMs: Int?
    /// Metadata cache max age.
    /// Defaults to topic.metadata.refresh.interval.ms * 3.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 86400000
    ///
    /// librdkafka property name: `"metadata.max.age.ms"`
    ///
    /// Default: 900000
    public var metadataMaxAgeMs: Int?
    /// When a topic loses its leader a new metadata request will be enqueued immediately and then with this initial interval, exponentially increasing upto `retry.backoff.max.ms`, until the topic metadata has been refreshed.
    /// If not set explicitly, it will be defaulted to `retry.backoff.ms`.
    /// This is used to recover quickly from transitioning leader brokers.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 60000
    ///
    /// librdkafka property name: `"topic.metadata.refresh.fast.interval.ms"`
    ///
    /// Default: 100
    public var topicMetadataRefreshFastIntervalMs: Int?
    /// Sparse metadata requests (consumes less network bandwidth).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"topic.metadata.refresh.sparse"`
    ///
    /// Default: True
    public var topicMetadataRefreshSparse: Bool?
    /// Apache Kafka topic creation is asynchronous and it takes some time for a new topic to propagate throughout the cluster to all brokers.
    /// If a client requests topic metadata after manual topic creation but before the topic has been fully propagated to the broker the client is requesting metadata from, the topic will seem to be non-existent and the client will mark the topic as such, failing queued produced messages with `ERR__UNKNOWN_TOPIC`.
    /// This setting delays marking a topic as non-existent until the configured propagation max time has passed.
    /// The maximum propagation time is calculated from the time the topic is first referenced in the client, e.g., on produce().
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"topic.metadata.propagation.max.ms"`
    ///
    /// Default: 30000
    public var topicMetadataPropagationMaxMs: Int?
    /// Topic ignore list, a comma-separated list of regular expressions for matching topic names that should be ignored in broker metadata information as if the topics did not exist.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"topic.blacklist"` // ignore-unacceptable-language
    public var topicIgnorelist: [String]?
    /// A comma-separated list of debug contexts to enable.
    /// Detailed Producer debugging: broker,topic,msg.
    /// Consumer: consumer,cgrp,topic,fetch.
    ///
    /// Importance: medium
    ///
    /// Values: `"generic"`, `"broker"`, `"topic"`, `"metadata"`, `"feature"`, `"queue"`, `"msg"`, `"protocol"`, `"cgrp"`, `"security"`, `"fetch"`, `"interceptor"`, `"plugin"`, `"consumer"`, `"admin"`, `"eos"`, `"mock"`, `"assignor"`, `"conf"`, `"telemetry"`, `"all"`
    ///
    /// librdkafka property name: `"debug"`
    public var debug: [KafkaConfig.Debug]?
    /// Default timeout for network requests.
    /// Producer: ProduceRequests will use the lesser value of `socket.timeout.ms` and remaining `message.timeout.ms` for the first message in the batch.
    /// Consumer: FetchRequests will use `fetch.wait.max.ms` + `socket.timeout.ms`.
    /// Admin: Admin requests will use `socket.timeout.ms` or explicitly set `rd_kafka_AdminOptions_set_operation_timeout()` value.
    ///
    /// Importance: low
    ///
    /// Value range: 10 .. 300000
    ///
    /// librdkafka property name: `"socket.timeout.ms"`
    ///
    /// Default: 60000
    public var socketTimeoutMs: Int?
    /// Broker socket send buffer size.
    /// System default is used if 0.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"socket.send.buffer.bytes"`
    public var socketSendBufferBytes: Int?
    /// Broker socket receive buffer size.
    /// System default is used if 0.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"socket.receive.buffer.bytes"`
    public var socketReceiveBufferBytes: Int?
    /// Enable TCP keep-alives (SO_KEEPALIVE) on broker sockets.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"socket.keepalive.enable"`
    ///
    /// Default: True
    public var socketKeepaliveEnable: Bool?
    /// Disable the Nagle algorithm (TCP_NODELAY) on broker sockets.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"socket.nagle.disable"`
    ///
    /// Default: True
    public var socketNagleDisable: Bool?
    /// Disconnect from broker when this number of send failures (e.g., timed out requests) is reached.
    /// Disable with 0.
    /// WARNING: It is highly recommended to leave this setting at its default value of 1 to avoid the client and broker to become desynchronized in case of request timeouts.
    /// NOTE: The connection is automatically re-established.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"socket.max.fails"`
    ///
    /// Default: 1
    public var socketMaxFails: Int?
    /// How long to cache the broker address resolving results (milliseconds).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"broker.address.ttl"`
    ///
    /// Default: 1000
    public var brokerAddressTtl: Int?
    /// Allowed broker IP address families: any, v4, v6.
    ///
    /// Importance: low
    ///
    /// Values: `"any"`, `"v4"`, `"v6"`
    ///
    /// librdkafka property name: `"broker.address.family"`
    ///
    /// Default: any
    public var brokerAddressFamily: KafkaConfig.BrokerAddressFamily?
    /// Maximum time allowed for broker connection setup (TCP connection setup as well SSL and SASL handshake).
    /// If the connection to the broker is not fully functional after this the connection will be closed and retried.
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 2147483647
    ///
    /// librdkafka property name: `"socket.connection.setup.timeout.ms"`
    ///
    /// Default: 30000
    public var socketConnectionSetupTimeoutMs: Int?
    /// Close broker connections after the specified time of inactivity.
    /// Disable with 0.
    /// If this property is left at its default value some heuristics are performed to determine a suitable default value, this is currently limited to identifying brokers on Azure (see librdkafka issue #3109 for more info).
    ///
    /// Importance: medium
    ///
    /// librdkafka property name: `"connections.max.idle.ms"`
    public var connectionsMaxIdleMs: Int?
    /// The initial time to wait before reconnecting to a broker after the connection has been closed.
    /// The time is increased exponentially until `reconnect.backoff.max.ms` is reached.
    /// -25% to +50% jitter is applied to each reconnect backoff.
    /// A value of 0 disables the backoff and reconnects immediately.
    ///
    /// Importance: medium
    ///
    /// librdkafka property name: `"reconnect.backoff.ms"`
    ///
    /// Default: 100
    public var reconnectBackoffMs: Int?
    /// The maximum time to wait before reconnecting to a broker after the connection has been closed.
    ///
    /// Importance: medium
    ///
    /// librdkafka property name: `"reconnect.backoff.max.ms"`
    ///
    /// Default: 10000
    public var reconnectBackoffMaxMs: Int?
    /// librdkafka statistics emit interval.
    /// The application also needs to register a stats callback using `rd_kafka_conf_set_stats_cb()`.
    /// The granularity is 1000ms.
    /// A value of 0 disables statistics.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"statistics.interval.ms"`
    public var statisticsIntervalMs: Int?
    /// See `rd_kafka_conf_set_events()`.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"enabled_events"`
    public var enabled_events: Int?
    /// Logging level (syslog(3) levels).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"log_level"`
    ///
    /// Default: 6
    public var log_level: Int?
    /// Disable spontaneous log_cb from internal librdkafka threads, instead enqueue log messages on queue set with `rd_kafka_set_log_queue()` and serve log callbacks or events through the standard poll APIs.
    /// **NOTE**: Log messages will linger in a temporary queue until the log queue has been set.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"log.queue"`
    ///
    /// Default: True
    public var logQueue: Bool?
    /// Print internal thread name in log messages (useful for debugging librdkafka internals).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"log.thread.name"`
    ///
    /// Default: True
    public var logThreadName: Bool?
    /// If enabled librdkafka will initialize the PRNG with srand(current_time.milliseconds) on the first invocation of rd_kafka_new() (required only if rand_r() is not available on your platform).
    /// If disabled the application must call srand() prior to calling rd_kafka_new().
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"enable.random.seed"`
    ///
    /// Default: True
    public var enableRandomSeed: Bool?
    /// Log broker disconnects.
    /// It might be useful to turn this off when interacting with 0.9 brokers with an aggressive `connections.max.idle.ms` value.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"log.connection.close"`
    ///
    /// Default: True
    public var logConnectionClose: Bool?
    /// Signal that librdkafka will use to quickly terminate on rd_kafka_destroy().
    /// If this signal is not set then there will be a delay before rd_kafka_wait_destroyed() returns true as internal threads are timing out their system calls.
    /// If this signal is set however the delay will be minimal.
    /// The application should mask this signal as an internal signal handler is installed.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"internal.termination.signal"`
    public var internalTerminationSignal: Int?
    /// Request broker's supported API versions to adjust functionality to available protocol features.
    /// If set to false, or the ApiVersionRequest fails, the fallback version `broker.version.fallback` will be used.
    /// **NOTE**: Depends on broker version >=0.10.0.
    /// If the request is not supported by (an older) broker the `broker.version.fallback` fallback is used.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"api.version.request"`
    ///
    /// Default: True
    public var apiVersionRequest: Bool?
    /// Timeout for broker API version requests.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 300000
    ///
    /// librdkafka property name: `"api.version.request.timeout.ms"`
    ///
    /// Default: 10000
    public var apiVersionRequestTimeoutMs: Int?
    /// Dictates how long the `broker.version.fallback` fallback is used in the case the ApiVersionRequest fails.
    /// **NOTE**: The ApiVersionRequest is only issued when a new connection to the broker is made (such as after an upgrade).
    ///
    /// Importance: medium
    ///
    /// librdkafka property name: `"api.version.fallback.ms"`
    public var apiVersionFallbackMs: Int?
    /// Older broker versions (before 0.10.0) provide no way for a client to query for supported protocol features (ApiVersionRequest, see `api.version.request`) making it impossible for the client to know what features it may use.
    /// As a workaround a user may set this property to the expected broker version and the client will automatically adjust its feature set accordingly if the ApiVersionRequest fails (or is disabled).
    /// The fallback broker version will be used for `api.version.fallback.ms`.
    /// Valid values are: 0.9.0, 0.8.2, 0.8.1, 0.8.0.
    /// Any other value >= 0.10, such as 0.10.2.1, enables ApiVersionRequests.
    ///
    /// Importance: medium
    ///
    /// librdkafka property name: `"broker.version.fallback"`
    ///
    /// Default: 0.10.0
    public var brokerVersionFallback: String?
    /// Allow automatic topic creation on the broker when subscribing to or assigning non-existent topics.
    /// The broker must also be configured with `auto.create.topics.enable=true` for this configuration to take effect.
    /// Note: the default value (true) for the producer is different from the default value (false) for the consumer.
    /// Further, the consumer default value is different from the Java consumer (true), and this property is not supported by the Java producer.
    /// Requires broker version >= 0.11.0.0, for older broker versions only the broker configuration applies.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"allow.auto.create.topics"`
    ///
    /// Default: True
    public var allowAutoCreateTopics: Bool?
    /// Protocol used to communicate with brokers.
    ///
    /// Importance: high
    ///
    /// Values: `"plaintext"`, `"ssl"`, `"sasl_plaintext"`, `"sasl_ssl"`
    ///
    /// librdkafka property name: `"security.protocol"`
    ///
    /// Default: plaintext
    public var securityProtocol: KafkaConfig.SecurityProtocol?
    /// A cipher suite is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol.
    /// See manual page for `ciphers(1)` and `SSL_CTX_set_cipher_list(3).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.cipher.suites"`
    public var sslCipherSuites: String?
    /// The supported-curves extension in the TLS ClientHello message specifies the curves (standard/named, or 'explicit' GF(2^k) or GF(p)) the client is willing to have the server use.
    /// See manual page for `SSL_CTX_set1_curves_list(3)`.
    /// OpenSSL >= 1.0.2 required.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.curves.list"`
    public var sslCurvesList: String?
    /// The client uses the TLS ClientHello signature_algorithms extension to indicate to the server which signature/hash algorithm pairs may be used in digital signatures.
    /// See manual page for `SSL_CTX_set1_sigalgs_list(3)`.
    /// OpenSSL >= 1.0.2 required.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.sigalgs.list"`
    public var sslSigalgsList: String?
    /// Path to client's private key (PEM) used for authentication.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.key.location"`
    public var sslKeyLocation: String?
    /// Private key passphrase (for use with `ssl.key.location` and `set_ssl_cert()`).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.key.password"`
    public var sslKeyPassword: String?
    /// Client's private key string (PEM format) used for authentication.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.key.pem"`
    public var sslKeyPem: String?
    /// Path to client's public key (PEM) used for authentication.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.certificate.location"`
    public var sslCertificateLocation: String?
    /// Client's public key string (PEM format) used for authentication.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.certificate.pem"`
    public var sslCertificatePem: String?
    /// File or directory path to CA certificate(s) for verifying the broker's key.
    /// Defaults: On Windows the system's CA certificates are automatically looked up in the Windows Root certificate store.
    /// On Mac OSX this configuration defaults to `probe`.
    /// It is recommended to install openssl using Homebrew, to provide CA certificates.
    /// On Linux install the distribution's ca-certificates package.
    /// If OpenSSL is statically linked or `ssl.ca.location` is set to `probe` a list of standard paths will be probed and the first one found will be used as the default CA certificate location path.
    /// If OpenSSL is dynamically linked the OpenSSL library's default path will be used (see `OPENSSLDIR` in `openssl version -a`).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.ca.location"`
    public var sslCaLocation: String?
    /// CA certificate string (PEM format) for verifying the broker's key.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.ca.pem"`
    public var sslCaPem: String?
    /// Comma-separated list of Windows Certificate stores to load CA certificates from.
    /// Certificates will be loaded in the same order as stores are specified.
    /// If no certificates can be loaded from any of the specified stores an error is logged and the OpenSSL library's default CA location is used instead.
    /// Store names are typically one or more of: MY, Root, Trust, CA.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.ca.certificate.stores"`
    ///
    /// Default: Root
    public var sslCaCertificateStores: String?
    /// Path to CRL for verifying broker's certificate validity.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.crl.location"`
    public var sslCrlLocation: String?
    /// Path to client's keystore (PKCS#12) used for authentication.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.keystore.location"`
    public var sslKeystoreLocation: String?
    /// Client's keystore (PKCS#12) password.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.keystore.password"`
    public var sslKeystorePassword: String?
    /// Comma-separated list of OpenSSL 3.0.x implementation providers.
    /// E.g., "default,legacy".
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.providers"`
    public var sslProviders: String?
    /// OpenSSL engine id is the name used for loading engine.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"ssl.engine.id"`
    ///
    /// Default: dynamic
    public var sslEngineId: String?
    /// Enable OpenSSL's builtin broker (server) certificate verification.
    /// This verification can be extended by the application by implementing a certificate_verify_cb.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"enable.ssl.certificate.verification"`
    ///
    /// Default: True
    public var enableSslCertificateVerification: Bool?
    /// Endpoint identification algorithm to validate broker hostname using broker certificate.
    /// https - Server (broker) hostname verification as specified in RFC2818.
    /// none - No endpoint verification.
    /// OpenSSL >= 1.0.2 required.
    ///
    /// Importance: low
    ///
    /// Values: `"none"`, `"https"`
    ///
    /// librdkafka property name: `"ssl.endpoint.identification.algorithm"`
    ///
    /// Default: https
    public var sslEndpointIdentificationAlgorithm: KafkaConfig.SslEndpointIdentificationAlgorithm?
    /// SASL mechanism to use for authentication.
    /// Supported: GSSAPI, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, OAUTHBEARER.
    /// **NOTE**: Despite the name only one mechanism must be configured.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"sasl.mechanisms"`
    ///
    /// Default: GSSAPI
    public var saslMechanisms: String?
    /// Alias for `sasl.mechanisms`: SASL mechanism to use for authentication.
    /// Supported: GSSAPI, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, OAUTHBEARER.
    /// **NOTE**: Despite the name only one mechanism must be configured.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"sasl.mechanism"`
    ///
    /// Default: GSSAPI
    public var saslMechanism: String?
    /// Kerberos principal name that Kafka runs as, not including /hostname@REALM.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.kerberos.service.name"`
    ///
    /// Default: kafka
    public var saslKerberosServiceName: String?
    /// This client's Kerberos principal name.
    /// (Not supported on Windows, will use the logon user's principal).
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.kerberos.principal"`
    ///
    /// Default: kafkaclient
    public var saslKerberosPrincipal: String?
    /// Shell command to refresh or acquire the client's Kerberos ticket.
    /// This command is executed on client creation and every sasl.kerberos.min.time.before.relogin (0=disable).
    /// %{config.prop.name} is replaced by corresponding config object value.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.kerberos.kinit.cmd"`
    ///
    /// Default: kinit -R -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal} \|\| kinit -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal}
    public var saslKerberosKinitCmd: String?
    /// Path to Kerberos keytab file.
    /// This configuration property is only used as a variable in `sasl.kerberos.kinit.cmd` as ` ..
    /// -t "%{sasl.kerberos.keytab}"`.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.kerberos.keytab"`
    public var saslKerberosKeytab: String?
    /// Minimum time in milliseconds between key refresh attempts.
    /// Disable automatic key refresh by setting this property to 0.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.kerberos.min.time.before.relogin"`
    ///
    /// Default: 60000
    public var saslKerberosMinTimeBeforeRelogin: Int?
    /// SASL username for use with the PLAIN and SASL-SCRAM-.
    /// mechanisms.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"sasl.username"`
    public var saslUsername: String?
    /// SASL password for use with the PLAIN and SASL-SCRAM-.
    /// mechanism.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"sasl.password"`
    public var saslPassword: String?
    /// SASL/OAUTHBEARER configuration.
    /// The format is implementation-dependent and must be parsed accordingly.
    /// The default unsecured token implementation (see https://tools.ietf.org/html/rfc7515#appendix-A.5) recognizes space-separated name=value pairs with valid names including principalClaimName, principal, scopeClaimName, scope, and lifeSeconds.
    /// The default value for principalClaimName is "sub", the default value for scopeClaimName is "scope", and the default value for lifeSeconds is 3600.
    /// The scope value is CSV format with the default value being no/empty scope.
    /// For example: `principalClaimName=azp principal=admin scopeClaimName=roles scope=role1,role2 lifeSeconds=600`.
    /// In addition, SASL extensions can be communicated to the broker via `extension_NAME=value`.
    /// For example: `principal=admin extension_traceId=123`.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.oauthbearer.config"`
    public var saslOauthbearerConfig: String?
    /// Enable the builtin unsecure JWT OAUTHBEARER token handler if no oauthbearer_refresh_cb has been set.
    /// This builtin handler should only be used for development or testing, and not in production.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"enable.sasl.oauthbearer.unsecure.jwt"`
    ///
    /// Default: True
    public var enableSaslOauthbearerUnsecureJwt: Bool?
    /// Set to "default" or "oidc" to control which login method to be used.
    /// If set to "oidc", the following properties must also be be specified: `sasl.oauthbearer.client.id`, `sasl.oauthbearer.client.secret`, and `sasl.oauthbearer.token.endpoint.url`.
    ///
    /// Importance: low
    ///
    /// Values: `"default"`, `"oidc"`
    ///
    /// librdkafka property name: `"sasl.oauthbearer.method"`
    ///
    /// Default: default
    public var saslOauthbearerMethod: KafkaConfig.SaslOauthbearerMethod?
    /// Public identifier for the application.
    /// Must be unique across all clients that the authorization server handles.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.oauthbearer.client.id"`
    public var saslOauthbearerClientId: String?
    /// Client secret only known to the application and the authorization server.
    /// This should be a sufficiently random string that is not guessable.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.oauthbearer.client.secret"`
    public var saslOauthbearerClientSecret: String?
    /// Client use this to specify the scope of the access request to the broker.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.oauthbearer.scope"`
    public var saslOauthbearerScope: String?
    /// Allow additional information to be provided to the broker.
    /// Comma-separated list of key=value pairs.
    /// E.g., "supportFeatureX=true,organizationId=sales-emea".Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.oauthbearer.extensions"`
    public var saslOauthbearerExtensions: String?
    /// OAuth/OIDC issuer token endpoint HTTP(S) URI used to retrieve token.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sasl.oauthbearer.token.endpoint.url"`
    public var saslOauthbearerTokenEndpointUrl: String?
    /// List of plugin libraries to load (; separated).
    /// The library search path is platform dependent (see dlopen(3) for Unix and LoadLibrary() for Windows).
    /// If no filename extension is specified the platform-specific extension (such as .dll or .so) will be appended automatically.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"plugin.library.paths"`
    public var pluginLibraryPaths: String?
    /// A rack identifier for this client.
    /// This can be any string value which indicates where this client is physically located.
    /// It corresponds with the broker config `broker.rack`.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"client.rack"`
    public var clientRack: String?
    /// Enables the transactional producer.
    /// The transactional.id is used to identify the same transactional producer instance across process restarts.
    /// It allows the producer to guarantee that transactions corresponding to earlier instances of the same producer have been finalized prior to starting any new transactions, and that any zombie instances are fenced off.
    /// If no transactional.id is provided, then the producer is limited to idempotent delivery (if enable.idempotence is set).
    /// Requires broker version >= 0.11.0.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"transactional.id"`
    public var transactionalId: String?
    /// The maximum amount of time in milliseconds that the transaction coordinator will wait for a transaction status update from the producer before proactively aborting the ongoing transaction.
    /// If this value is larger than the `transaction.max.timeout.ms` setting in the broker, the init_transactions() call will fail with ERR_INVALID_TRANSACTION_TIMEOUT.
    /// The transaction timeout automatically adjusts `message.timeout.ms` and `socket.timeout.ms`, unless explicitly configured in which case they must not exceed the transaction timeout (`socket.timeout.ms` must be at least 100ms lower than `transaction.timeout.ms`).
    /// This is also the default timeout value if no timeout (-1) is supplied to the transactional API methods.
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 2147483647
    ///
    /// librdkafka property name: `"transaction.timeout.ms"`
    ///
    /// Default: 60000
    public var transactionTimeoutMs: Int?
    /// When set to `true`, the producer will ensure that messages are successfully produced exactly once and in the original produce order.
    /// The following configuration properties are adjusted automatically (if not modified by the user) when idempotence is enabled: `max.in.flight.requests.per.connection=5` (must be less than or equal to 5), `retries=INT32_MAX` (must be greater than 0), `acks=all`, `queuing.strategy=fifo`.
    /// Producer instantation will fail if user-supplied configuration is incompatible.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"enable.idempotence"`
    ///
    /// Default: True
    public var enableIdempotence: Bool?
    /// **EXPERIMENTAL**: subject to change or removal.
    /// When set to `true`, any error that could result in a gap in the produced message series when a batch of messages fails, will raise a fatal error (ERR__GAPLESS_GUARANTEE) and stop the producer.
    /// Messages failing due to `message.timeout.ms` are not covered by this guarantee.
    /// Requires `enable.idempotence=true`.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"enable.gapless.guarantee"`
    ///
    /// Default: True
    public var enableGaplessGuarantee: Bool?
    /// Maximum number of messages allowed on the producer queue.
    /// This queue is shared by all topics and partitions.
    /// A value of 0 disables this limit.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"queue.buffering.max.messages"`
    ///
    /// Default: 100000
    public var queueBufferingMaxMessages: Int?
    /// Maximum total message size sum allowed on the producer queue.
    /// This queue is shared by all topics and partitions.
    /// This property has higher priority than queue.buffering.max.messages.
    ///
    /// Importance: high
    ///
    /// Value range: 1 .. 2147483647
    ///
    /// librdkafka property name: `"queue.buffering.max.kbytes"`
    ///
    /// Default: 1048576
    public var queueBufferingMaxKbytes: Int?
    /// Delay in milliseconds to wait for messages in the producer queue to accumulate before constructing message batches (MessageSets) to transmit to brokers.
    /// A higher value allows larger and more effective (less overhead, improved compression) batches of messages to accumulate at the expense of increased message delivery latency.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"queue.buffering.max.ms"`
    ///
    /// Default: 5.0
    public var queueBufferingMaxMs: Double?
    /// Alias for `queue.buffering.max.ms`: Delay in milliseconds to wait for messages in the producer queue to accumulate before constructing message batches (MessageSets) to transmit to brokers.
    /// A higher value allows larger and more effective (less overhead, improved compression) batches of messages to accumulate at the expense of increased message delivery latency.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"linger.ms"`
    ///
    /// Default: 5.0
    public var lingerMs: Double?
    /// How many times to retry sending a failing Message.
    /// **Note:** retrying may cause reordering unless `enable.idempotence` is set to true.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"message.send.max.retries"`
    ///
    /// Default: 2147483647
    public var messageSendMaxRetries: Int?
    /// Alias for `message.send.max.retries`: How many times to retry sending a failing Message.
    /// **Note:** retrying may cause reordering unless `enable.idempotence` is set to true.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"retries"`
    ///
    /// Default: 2147483647
    public var retries: Int?
    /// The backoff time in milliseconds before retrying a protocol request, this is the first backoff time, and will be backed off exponentially until number of retries is exhausted, and it's capped by retry.backoff.max.ms.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 300000
    ///
    /// librdkafka property name: `"retry.backoff.ms"`
    ///
    /// Default: 100
    public var retryBackoffMs: Int?
    /// The max backoff time in milliseconds before retrying a protocol request, this is the atmost backoff allowed for exponentially backed off requests.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 300000
    ///
    /// librdkafka property name: `"retry.backoff.max.ms"`
    ///
    /// Default: 1000
    public var retryBackoffMaxMs: Int?
    /// The threshold of outstanding not yet transmitted broker requests needed to backpressure the producer's message accumulator.
    /// If the number of not yet transmitted requests equals or exceeds this number, produce request creation that would have otherwise been triggered (for example, in accordance with linger.ms) will be delayed.
    /// A lower number yields larger and more effective batches.
    /// A higher value can improve latency when using compression on slow machines.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 1000000
    ///
    /// librdkafka property name: `"queue.buffering.backpressure.threshold"`
    ///
    /// Default: 1
    public var queueBufferingBackpressureThreshold: Int?
    /// compression codec to use for compressing message sets.
    /// This is the default value for all topics, may be overridden by the topic configuration property `compression.codec`.
    ///
    /// Importance: medium
    ///
    /// Values: `"none"`, `"gzip"`, `"snappy"`, `"lz4"`, `"zstd"`
    ///
    /// librdkafka property name: `"compression.codec"`
    ///
    /// Default: none
    public var compressionCodec: KafkaConfig.CompressionCodec?
    /// Alias for `compression.codec`: compression codec to use for compressing message sets.
    /// This is the default value for all topics, may be overridden by the topic configuration property `compression.codec`.
    ///
    /// Importance: medium
    ///
    /// Values: `"none"`, `"gzip"`, `"snappy"`, `"lz4"`, `"zstd"`
    ///
    /// librdkafka property name: `"compression.type"`
    ///
    /// Default: none
    public var compressionType: KafkaConfig.CompressionType?
    /// Maximum number of messages batched in one MessageSet.
    /// The total MessageSet size is also limited by batch.size and message.max.bytes.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 1000000
    ///
    /// librdkafka property name: `"batch.num.messages"`
    ///
    /// Default: 10000
    public var batchNumMessages: Int?
    /// Maximum size (in bytes) of all messages batched in one MessageSet, including protocol framing overhead.
    /// This limit is applied after the first message has been added to the batch, regardless of the first message's size, this is to ensure that messages that exceed batch.size are produced.
    /// The total MessageSet size is also limited by batch.num.messages and message.max.bytes.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 2147483647
    ///
    /// librdkafka property name: `"batch.size"`
    ///
    /// Default: 1000000
    public var batchSize: Int?
    /// Only provide delivery reports for failed messages.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"delivery.report.only.error"`
    ///
    /// Default: True
    public var deliveryReportOnlyError: Bool?
    /// Delay in milliseconds to wait to assign new sticky partitions for each topic.
    /// By default, set to double the time of linger.ms.
    /// To disable sticky behavior, set to 0.
    /// This behavior affects messages with the key NULL in all cases, and messages with key lengths of zero when the consistent_random partitioner is in use.
    /// These messages would otherwise be assigned randomly.
    /// A higher value allows for more effective batching of these messages.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"sticky.partitioning.linger.ms"`
    ///
    /// Default: 10
    public var stickyPartitioningLingerMs: Int?
    /// Controls how the client uses DNS lookups.
    /// By default, when the lookup returns multiple IP addresses for a hostname, they will all be attempted for connection before the connection is considered failed.
    /// This applies to both bootstrap and advertised servers.
    /// If the value is set to `resolve_canonical_bootstrap_servers_only`, each entry will be resolved and expanded into a list of canonical names.
    /// **WARNING**: `resolve_canonical_bootstrap_servers_only` must only be used with `GSSAPI` (Kerberos) as `sasl.mechanism`, as it's the only purpose of this configuration value.
    /// **NOTE**: Default here is different from the Java client's default behavior, which connects only to the first IP address returned for a hostname.
    ///
    /// Importance: low
    ///
    /// Values: `"use_all_dns_ips"`, `"resolve_canonical_bootstrap_servers_only"`
    ///
    /// librdkafka property name: `"client.dns.lookup"`
    ///
    /// Default: use_all_dns_ips
    public var clientDnsLookup: KafkaConfig.ClientDnsLookup?
    /// Whether to enable pushing of client metrics to the cluster, if the cluster has a client metrics subscription which matches this client.
    ///
    /// Importance: low
    ///
    /// librdkafka property name: `"enable.metrics.push"`
    ///
    /// Default: True
    public var enableMetricsPush: Bool?
    /// This field indicates the number of acknowledgements the leader broker must receive from ISR brokers before responding to the request: *0*=Broker does not send any response/ack to client, *-1* or *all*=Broker will block until message is committed by all in sync replicas (ISRs).
    /// If there are less than `min.insync.replicas` (broker configuration) in the ISR set the produce request will fail.
    ///
    /// Importance: high
    ///
    /// Value range: -1 .. 1000
    ///
    /// librdkafka property name: `"request.required.acks"`
    ///
    /// Default: -1
    public var requestRequiredAcks: Int?
    /// Alias for `request.required.acks`: This field indicates the number of acknowledgements the leader broker must receive from ISR brokers before responding to the request: *0*=Broker does not send any response/ack to client, *-1* or *all*=Broker will block until message is committed by all in sync replicas (ISRs).
    /// If there are less than `min.insync.replicas` (broker configuration) in the ISR set the produce request will fail.
    ///
    /// Importance: high
    ///
    /// Value range: -1 .. 1000
    ///
    /// librdkafka property name: `"acks"`
    ///
    /// Default: -1
    public var acks: Int?
    /// The ack timeout of the producer request in milliseconds.
    /// This value is only enforced by the broker and relies on `request.required.acks` being != 0.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 900000
    ///
    /// librdkafka property name: `"request.timeout.ms"`
    ///
    /// Default: 30000
    public var requestTimeoutMs: Int?
    /// Local message timeout.
    /// This value is only enforced locally and limits the time a produced message waits for successful delivery.
    /// A time of 0 is infinite.
    /// This is the maximum time librdkafka may use to deliver a message (including retries).
    /// Delivery error occurs when either the retry count or the message timeout are exceeded.
    /// The message timeout is automatically adjusted to `transaction.timeout.ms` if `transactional.id` is configured.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"message.timeout.ms"`
    ///
    /// Default: 300000
    public var messageTimeoutMs: Int?
    /// Alias for `message.timeout.ms`: Local message timeout.
    /// This value is only enforced locally and limits the time a produced message waits for successful delivery.
    /// A time of 0 is infinite.
    /// This is the maximum time librdkafka may use to deliver a message (including retries).
    /// Delivery error occurs when either the retry count or the message timeout are exceeded.
    /// The message timeout is automatically adjusted to `transaction.timeout.ms` if `transactional.id` is configured.
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"delivery.timeout.ms"`
    ///
    /// Default: 300000
    public var deliveryTimeoutMs: Int?
    /// Partitioner: `random` - random distribution, `consistent` - CRC32 hash of key (Empty and NULL keys are mapped to single partition), `consistent_random` - CRC32 hash of key (Empty and NULL keys are randomly partitioned), `murmur2` - Java Producer compatible Murmur2 hash of key (NULL keys are mapped to single partition), `murmur2_random` - Java Producer compatible Murmur2 hash of key (NULL keys are randomly partitioned.
    /// This is functionally equivalent to the default partitioner in the Java Producer.), `fnv1a` - FNV-1a hash of key (NULL keys are mapped to single partition), `fnv1a_random` - FNV-1a hash of key (NULL keys are randomly partitioned).
    ///
    /// Importance: high
    ///
    /// librdkafka property name: `"partitioner"`
    ///
    /// Default: consistent_random
    public var partitioner: String?
    /// Compression level parameter for algorithm selected by configuration property `compression.codec`.
    /// Higher values will result in better compression at the cost of more CPU usage.
    /// Usable range is algorithm-dependent: [0-9] for gzip; [0-12] for lz4; only 0 for snappy; -1 = codec-dependent default compression level.
    ///
    /// Importance: medium
    ///
    /// Value range: -1 .. 12
    ///
    /// librdkafka property name: `"compression.level"`
    ///
    /// Default: -1
    public var compressionLevel: Int?

    /// Additional librdkafka configuration properties not covered by typed properties.
    /// Keys and values are passed directly to librdkafka.
    internal var additionalConfig: [String: String] = [:]

    public init() {}

    internal var config: [String: String] {
        var config: [String: String] = [:]

        config["client.id"] = self.clientId?.description
        config["metadata.broker.list"] = self.metadataBrokerList?.joined(separator: ",")
        config["bootstrap.servers"] = self.bootstrapServers?.joined(separator: ",")
        config["message.max.bytes"] = self.messageMaxBytes?.description
        config["message.copy.max.bytes"] = self.messageCopyMaxBytes?.description
        config["receive.message.max.bytes"] = self.receiveMessageMaxBytes?.description
        config["max.in.flight.requests.per.connection"] = self.maxInFlightRequestsPerConnection?.description
        config["max.in.flight"] = self.maxInFlight?.description
        config["topic.metadata.refresh.interval.ms"] = self.topicMetadataRefreshIntervalMs?.description
        config["metadata.max.age.ms"] = self.metadataMaxAgeMs?.description
        config["topic.metadata.refresh.fast.interval.ms"] = self.topicMetadataRefreshFastIntervalMs?.description
        config["topic.metadata.refresh.sparse"] = self.topicMetadataRefreshSparse?.description
        config["topic.metadata.propagation.max.ms"] = self.topicMetadataPropagationMaxMs?.description
        config["topic.blacklist"] = self.topicIgnorelist?.joined(separator: ",")  // ignore-unacceptable-language
        config["debug"] = self.debug?.map(\.description).joined(separator: ",")
        config["socket.timeout.ms"] = self.socketTimeoutMs?.description
        config["socket.send.buffer.bytes"] = self.socketSendBufferBytes?.description
        config["socket.receive.buffer.bytes"] = self.socketReceiveBufferBytes?.description
        config["socket.keepalive.enable"] = self.socketKeepaliveEnable?.description
        config["socket.nagle.disable"] = self.socketNagleDisable?.description
        config["socket.max.fails"] = self.socketMaxFails?.description
        config["broker.address.ttl"] = self.brokerAddressTtl?.description
        config["broker.address.family"] = self.brokerAddressFamily?.description
        config["socket.connection.setup.timeout.ms"] = self.socketConnectionSetupTimeoutMs?.description
        config["connections.max.idle.ms"] = self.connectionsMaxIdleMs?.description
        config["reconnect.backoff.ms"] = self.reconnectBackoffMs?.description
        config["reconnect.backoff.max.ms"] = self.reconnectBackoffMaxMs?.description
        config["statistics.interval.ms"] = self.statisticsIntervalMs?.description
        config["enabled_events"] = self.enabled_events?.description
        config["log_level"] = self.log_level?.description
        config["log.queue"] = self.logQueue?.description
        config["log.thread.name"] = self.logThreadName?.description
        config["enable.random.seed"] = self.enableRandomSeed?.description
        config["log.connection.close"] = self.logConnectionClose?.description
        config["internal.termination.signal"] = self.internalTerminationSignal?.description
        config["api.version.request"] = self.apiVersionRequest?.description
        config["api.version.request.timeout.ms"] = self.apiVersionRequestTimeoutMs?.description
        config["api.version.fallback.ms"] = self.apiVersionFallbackMs?.description
        config["broker.version.fallback"] = self.brokerVersionFallback?.description
        config["allow.auto.create.topics"] = self.allowAutoCreateTopics?.description
        config["security.protocol"] = self.securityProtocol?.description
        config["ssl.cipher.suites"] = self.sslCipherSuites?.description
        config["ssl.curves.list"] = self.sslCurvesList?.description
        config["ssl.sigalgs.list"] = self.sslSigalgsList?.description
        config["ssl.key.location"] = self.sslKeyLocation?.description
        config["ssl.key.password"] = self.sslKeyPassword?.description
        config["ssl.key.pem"] = self.sslKeyPem?.description
        config["ssl.certificate.location"] = self.sslCertificateLocation?.description
        config["ssl.certificate.pem"] = self.sslCertificatePem?.description
        config["ssl.ca.location"] = self.sslCaLocation?.description
        config["ssl.ca.pem"] = self.sslCaPem?.description
        config["ssl.ca.certificate.stores"] = self.sslCaCertificateStores?.description
        config["ssl.crl.location"] = self.sslCrlLocation?.description
        config["ssl.keystore.location"] = self.sslKeystoreLocation?.description
        config["ssl.keystore.password"] = self.sslKeystorePassword?.description
        config["ssl.providers"] = self.sslProviders?.description
        config["ssl.engine.id"] = self.sslEngineId?.description
        config["enable.ssl.certificate.verification"] = self.enableSslCertificateVerification?.description
        config["ssl.endpoint.identification.algorithm"] = self.sslEndpointIdentificationAlgorithm?.description
        config["sasl.mechanisms"] = self.saslMechanisms?.description
        config["sasl.mechanism"] = self.saslMechanism?.description
        config["sasl.kerberos.service.name"] = self.saslKerberosServiceName?.description
        config["sasl.kerberos.principal"] = self.saslKerberosPrincipal?.description
        config["sasl.kerberos.kinit.cmd"] = self.saslKerberosKinitCmd?.description
        config["sasl.kerberos.keytab"] = self.saslKerberosKeytab?.description
        config["sasl.kerberos.min.time.before.relogin"] = self.saslKerberosMinTimeBeforeRelogin?.description
        config["sasl.username"] = self.saslUsername?.description
        config["sasl.password"] = self.saslPassword?.description
        config["sasl.oauthbearer.config"] = self.saslOauthbearerConfig?.description
        config["enable.sasl.oauthbearer.unsecure.jwt"] = self.enableSaslOauthbearerUnsecureJwt?.description
        config["sasl.oauthbearer.method"] = self.saslOauthbearerMethod?.description
        config["sasl.oauthbearer.client.id"] = self.saslOauthbearerClientId?.description
        config["sasl.oauthbearer.client.secret"] = self.saslOauthbearerClientSecret?.description
        config["sasl.oauthbearer.scope"] = self.saslOauthbearerScope?.description
        config["sasl.oauthbearer.extensions"] = self.saslOauthbearerExtensions?.description
        config["sasl.oauthbearer.token.endpoint.url"] = self.saslOauthbearerTokenEndpointUrl?.description
        config["plugin.library.paths"] = self.pluginLibraryPaths?.description
        config["client.rack"] = self.clientRack?.description
        config["transactional.id"] = self.transactionalId?.description
        config["transaction.timeout.ms"] = self.transactionTimeoutMs?.description
        config["enable.idempotence"] = self.enableIdempotence?.description
        config["enable.gapless.guarantee"] = self.enableGaplessGuarantee?.description
        config["queue.buffering.max.messages"] = self.queueBufferingMaxMessages?.description
        config["queue.buffering.max.kbytes"] = self.queueBufferingMaxKbytes?.description
        config["queue.buffering.max.ms"] = self.queueBufferingMaxMs?.description
        config["linger.ms"] = self.lingerMs?.description
        config["message.send.max.retries"] = self.messageSendMaxRetries?.description
        config["retries"] = self.retries?.description
        config["retry.backoff.ms"] = self.retryBackoffMs?.description
        config["retry.backoff.max.ms"] = self.retryBackoffMaxMs?.description
        config["queue.buffering.backpressure.threshold"] = self.queueBufferingBackpressureThreshold?.description
        config["compression.codec"] = self.compressionCodec?.description
        config["compression.type"] = self.compressionType?.description
        config["batch.num.messages"] = self.batchNumMessages?.description
        config["batch.size"] = self.batchSize?.description
        config["delivery.report.only.error"] = self.deliveryReportOnlyError?.description
        config["sticky.partitioning.linger.ms"] = self.stickyPartitioningLingerMs?.description
        config["client.dns.lookup"] = self.clientDnsLookup?.description
        config["enable.metrics.push"] = self.enableMetricsPush?.description
        config["request.required.acks"] = self.requestRequiredAcks?.description
        config["acks"] = self.acks?.description
        config["request.timeout.ms"] = self.requestTimeoutMs?.description
        config["message.timeout.ms"] = self.messageTimeoutMs?.description
        config["delivery.timeout.ms"] = self.deliveryTimeoutMs?.description
        config["partitioner"] = self.partitioner?.description
        config["compression.level"] = self.compressionLevel?.description

        if config["statistics.interval.ms"] == nil,
            metrics.enabled,
            let updateInterval = metrics.updateInterval
        {
            config["statistics.interval.ms"] = String(updateInterval.inMilliseconds)
        }

        for (key, value) in self.additionalConfig {
            config[key] = value
        }

        return config
    }

    // swift-format-ignore
    internal init(_ configDict: [String: String]) {
        self.clientId = configDict["client.id"]
        self.metadataBrokerList = configDict["metadata.broker.list"]?.components(separatedBy: ",")
        self.bootstrapServers = configDict["bootstrap.servers"]?.components(separatedBy: ",")
        self.messageMaxBytes = Int(configDict["message.max.bytes"] ?? "")
        self.messageCopyMaxBytes = Int(configDict["message.copy.max.bytes"] ?? "")
        self.receiveMessageMaxBytes = Int(configDict["receive.message.max.bytes"] ?? "")
        self.maxInFlightRequestsPerConnection = Int(configDict["max.in.flight.requests.per.connection"] ?? "")
        self.maxInFlight = Int(configDict["max.in.flight"] ?? "")
        self.topicMetadataRefreshIntervalMs = Int(configDict["topic.metadata.refresh.interval.ms"] ?? "")
        self.metadataMaxAgeMs = Int(configDict["metadata.max.age.ms"] ?? "")
        self.topicMetadataRefreshFastIntervalMs = Int(configDict["topic.metadata.refresh.fast.interval.ms"] ?? "")
        self.topicMetadataRefreshSparse = Bool(configDict["topic.metadata.refresh.sparse"] ?? "")
        self.topicMetadataPropagationMaxMs = Int(configDict["topic.metadata.propagation.max.ms"] ?? "")
        self.topicIgnorelist = configDict["topic.blacklist"]?.components(separatedBy: ",") // ignore-unacceptable-language
        self.debug = configDict["debug"]?.components(separatedBy: ",").map { KafkaConfig.Debug(description: $0) }
        self.socketTimeoutMs = Int(configDict["socket.timeout.ms"] ?? "")
        self.socketSendBufferBytes = Int(configDict["socket.send.buffer.bytes"] ?? "")
        self.socketReceiveBufferBytes = Int(configDict["socket.receive.buffer.bytes"] ?? "")
        self.socketKeepaliveEnable = Bool(configDict["socket.keepalive.enable"] ?? "")
        self.socketNagleDisable = Bool(configDict["socket.nagle.disable"] ?? "")
        self.socketMaxFails = Int(configDict["socket.max.fails"] ?? "")
        self.brokerAddressTtl = Int(configDict["broker.address.ttl"] ?? "")
        self.brokerAddressFamily = configDict["broker.address.family"].map(KafkaConfig.BrokerAddressFamily.init)
        self.socketConnectionSetupTimeoutMs = Int(configDict["socket.connection.setup.timeout.ms"] ?? "")
        self.connectionsMaxIdleMs = Int(configDict["connections.max.idle.ms"] ?? "")
        self.reconnectBackoffMs = Int(configDict["reconnect.backoff.ms"] ?? "")
        self.reconnectBackoffMaxMs = Int(configDict["reconnect.backoff.max.ms"] ?? "")
        self.statisticsIntervalMs = Int(configDict["statistics.interval.ms"] ?? "")
        self.enabled_events = Int(configDict["enabled_events"] ?? "")
        self.log_level = Int(configDict["log_level"] ?? "")
        self.logQueue = Bool(configDict["log.queue"] ?? "")
        self.logThreadName = Bool(configDict["log.thread.name"] ?? "")
        self.enableRandomSeed = Bool(configDict["enable.random.seed"] ?? "")
        self.logConnectionClose = Bool(configDict["log.connection.close"] ?? "")
        self.internalTerminationSignal = Int(configDict["internal.termination.signal"] ?? "")
        self.apiVersionRequest = Bool(configDict["api.version.request"] ?? "")
        self.apiVersionRequestTimeoutMs = Int(configDict["api.version.request.timeout.ms"] ?? "")
        self.apiVersionFallbackMs = Int(configDict["api.version.fallback.ms"] ?? "")
        self.brokerVersionFallback = configDict["broker.version.fallback"]
        self.allowAutoCreateTopics = Bool(configDict["allow.auto.create.topics"] ?? "")
        self.securityProtocol = configDict["security.protocol"].map(KafkaConfig.SecurityProtocol.init)
        self.sslCipherSuites = configDict["ssl.cipher.suites"]
        self.sslCurvesList = configDict["ssl.curves.list"]
        self.sslSigalgsList = configDict["ssl.sigalgs.list"]
        self.sslKeyLocation = configDict["ssl.key.location"]
        self.sslKeyPassword = configDict["ssl.key.password"]
        self.sslKeyPem = configDict["ssl.key.pem"]
        self.sslCertificateLocation = configDict["ssl.certificate.location"]
        self.sslCertificatePem = configDict["ssl.certificate.pem"]
        self.sslCaLocation = configDict["ssl.ca.location"]
        self.sslCaPem = configDict["ssl.ca.pem"]
        self.sslCaCertificateStores = configDict["ssl.ca.certificate.stores"]
        self.sslCrlLocation = configDict["ssl.crl.location"]
        self.sslKeystoreLocation = configDict["ssl.keystore.location"]
        self.sslKeystorePassword = configDict["ssl.keystore.password"]
        self.sslProviders = configDict["ssl.providers"]
        self.sslEngineId = configDict["ssl.engine.id"]
        self.enableSslCertificateVerification = Bool(configDict["enable.ssl.certificate.verification"] ?? "")
        self.sslEndpointIdentificationAlgorithm = configDict["ssl.endpoint.identification.algorithm"].map(KafkaConfig.SslEndpointIdentificationAlgorithm.init)
        self.saslMechanisms = configDict["sasl.mechanisms"]
        self.saslMechanism = configDict["sasl.mechanism"]
        self.saslKerberosServiceName = configDict["sasl.kerberos.service.name"]
        self.saslKerberosPrincipal = configDict["sasl.kerberos.principal"]
        self.saslKerberosKinitCmd = configDict["sasl.kerberos.kinit.cmd"]
        self.saslKerberosKeytab = configDict["sasl.kerberos.keytab"]
        self.saslKerberosMinTimeBeforeRelogin = Int(configDict["sasl.kerberos.min.time.before.relogin"] ?? "")
        self.saslUsername = configDict["sasl.username"]
        self.saslPassword = configDict["sasl.password"]
        self.saslOauthbearerConfig = configDict["sasl.oauthbearer.config"]
        self.enableSaslOauthbearerUnsecureJwt = Bool(configDict["enable.sasl.oauthbearer.unsecure.jwt"] ?? "")
        self.saslOauthbearerMethod = configDict["sasl.oauthbearer.method"].map(KafkaConfig.SaslOauthbearerMethod.init)
        self.saslOauthbearerClientId = configDict["sasl.oauthbearer.client.id"]
        self.saslOauthbearerClientSecret = configDict["sasl.oauthbearer.client.secret"]
        self.saslOauthbearerScope = configDict["sasl.oauthbearer.scope"]
        self.saslOauthbearerExtensions = configDict["sasl.oauthbearer.extensions"]
        self.saslOauthbearerTokenEndpointUrl = configDict["sasl.oauthbearer.token.endpoint.url"]
        self.pluginLibraryPaths = configDict["plugin.library.paths"]
        self.clientRack = configDict["client.rack"]
        self.transactionalId = configDict["transactional.id"]
        self.transactionTimeoutMs = Int(configDict["transaction.timeout.ms"] ?? "")
        self.enableIdempotence = Bool(configDict["enable.idempotence"] ?? "")
        self.enableGaplessGuarantee = Bool(configDict["enable.gapless.guarantee"] ?? "")
        self.queueBufferingMaxMessages = Int(configDict["queue.buffering.max.messages"] ?? "")
        self.queueBufferingMaxKbytes = Int(configDict["queue.buffering.max.kbytes"] ?? "")
        self.queueBufferingMaxMs = Double(configDict["queue.buffering.max.ms"] ?? "")
        self.lingerMs = Double(configDict["linger.ms"] ?? "")
        self.messageSendMaxRetries = Int(configDict["message.send.max.retries"] ?? "")
        self.retries = Int(configDict["retries"] ?? "")
        self.retryBackoffMs = Int(configDict["retry.backoff.ms"] ?? "")
        self.retryBackoffMaxMs = Int(configDict["retry.backoff.max.ms"] ?? "")
        self.queueBufferingBackpressureThreshold = Int(configDict["queue.buffering.backpressure.threshold"] ?? "")
        self.compressionCodec = configDict["compression.codec"].map(KafkaConfig.CompressionCodec.init)
        self.compressionType = configDict["compression.type"].map(KafkaConfig.CompressionType.init)
        self.batchNumMessages = Int(configDict["batch.num.messages"] ?? "")
        self.batchSize = Int(configDict["batch.size"] ?? "")
        self.deliveryReportOnlyError = Bool(configDict["delivery.report.only.error"] ?? "")
        self.stickyPartitioningLingerMs = Int(configDict["sticky.partitioning.linger.ms"] ?? "")
        self.clientDnsLookup = configDict["client.dns.lookup"].map(KafkaConfig.ClientDnsLookup.init)
        self.enableMetricsPush = Bool(configDict["enable.metrics.push"] ?? "")
        self.requestRequiredAcks = Int(configDict["request.required.acks"] ?? "")
        self.acks = Int(configDict["acks"] ?? "")
        self.requestTimeoutMs = Int(configDict["request.timeout.ms"] ?? "")
        self.messageTimeoutMs = Int(configDict["message.timeout.ms"] ?? "")
        self.deliveryTimeoutMs = Int(configDict["delivery.timeout.ms"] ?? "")
        self.partitioner = configDict["partitioner"]
        self.compressionLevel = Int(configDict["compression.level"] ?? "")
    }
}
