//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-kafka-client open source project
//
// Copyright (c) 2026 Apple Inc. and the swift-kafka-client project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-kafka-client project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################

import struct Foundation.UUID

public enum KafkaConfig {
    /// A comma-separated list of debug contexts to enable.
    /// Detailed Producer debugging: broker,topic,msg.
    /// Consumer: consumer,cgrp,topic,fetch.
    public enum Debug: String, Sendable {
        case `generic` = "generic"
        case `broker` = "broker"
        case `topic` = "topic"
        case `metadata` = "metadata"
        case `feature` = "feature"
        case `queue` = "queue"
        case `msg` = "msg"
        case `protocol` = "protocol"
        case `cgrp` = "cgrp"
        case `security` = "security"
        case `fetch` = "fetch"
        case `interceptor` = "interceptor"
        case `plugin` = "plugin"
        case `consumer` = "consumer"
        case `admin` = "admin"
        case `eos` = "eos"
        case `mock` = "mock"
        case `assignor` = "assignor"
        case `conf` = "conf"
        case `telemetry` = "telemetry"
        case `all` = "all"
    }
    /// Allowed broker IP address families: any, v4, v6.
    public enum BrokerAddressFamily: String, Sendable {
        case `any` = "any"
        case `v4` = "v4"
        case `v6` = "v6"
    }
    /// Protocol used to communicate with brokers.
    public enum SecurityProtocol: String, Sendable {
        case `plaintext` = "plaintext"
        case `ssl` = "ssl"
        case `sasl_plaintext` = "sasl_plaintext"
        case `sasl_ssl` = "sasl_ssl"
    }
    /// Endpoint identification algorithm to validate broker hostname using broker certificate.
    /// https - Server (broker) hostname verification as specified in RFC2818.
    /// none - No endpoint verification.
    /// OpenSSL >= 1.0.2 required.
    public enum SslEndpointIdentificationAlgorithm: String, Sendable {
        case `none` = "none"
        case `https` = "https"
    }
    /// Set to "default" or "oidc" to control which login method to be used.
    /// If set to "oidc", the following properties must also be be specified: `sasl.oauthbearer.client.id`, `sasl.oauthbearer.client.secret`, and `sasl.oauthbearer.token.endpoint.url`.
    public enum SaslOauthbearerMethod: String, Sendable {
        case `default` = "default"
        case `oidc` = "oidc"
    }
    /// Group protocol to use.
    /// Use `classic` for the original protocol and `consumer` for the new protocol introduced in KIP-848.
    /// Available protocols: classic or consumer.
    /// Default is `classic`, but will change to `consumer` in next releases.
    public enum GroupProtocol: String, Sendable {
        case `classic` = "classic"
        case `consumer` = "consumer"
    }
    /// Controls how to read messages written transactionally: `read_committed` - only return transactional messages which have been committed.
    /// `read_uncommitted` - return all messages, even transactional messages which have been aborted.
    public enum IsolationLevel: String, Sendable {
        case `read_uncommitted` = "read_uncommitted"
        case `read_committed` = "read_committed"
    }
    /// compression codec to use for compressing message sets.
    /// This is the default value for all topics, may be overridden by the topic configuration property `compression.codec`.
    public enum CompressionCodec: String, Sendable {
        case `none` = "none"
        case `gzip` = "gzip"
        case `snappy` = "snappy"
        case `lz4` = "lz4"
        case `zstd` = "zstd"
    }
    /// Alias for `compression.codec`: compression codec to use for compressing message sets.
    /// This is the default value for all topics, may be overridden by the topic configuration property `compression.codec`.
    public enum CompressionType: String, Sendable {
        case `none` = "none"
        case `gzip` = "gzip"
        case `snappy` = "snappy"
        case `lz4` = "lz4"
        case `zstd` = "zstd"
    }
    /// Controls how the client uses DNS lookups.
    /// By default, when the lookup returns multiple IP addresses for a hostname, they will all be attempted for connection before the connection is considered failed.
    /// This applies to both bootstrap and advertised servers.
    /// If the value is set to `resolve_canonical_bootstrap_servers_only`, each entry will be resolved and expanded into a list of canonical names.
    /// **WARNING**: `resolve_canonical_bootstrap_servers_only` must only be used with `GSSAPI` (Kerberos) as `sasl.mechanism`, as it's the only purpose of this configuration value.
    /// **NOTE**: Default here is different from the Java client's default behavior, which connects only to the first IP address returned for a hostname.
    public enum ClientDnsLookup: String, Sendable {
        case `use_all_dns_ips` = "use_all_dns_ips"
        case `resolve_canonical_bootstrap_servers_only` = "resolve_canonical_bootstrap_servers_only"
    }
    /// Action to take when there is no initial offset in offset store or the desired offset is out of range: 'smallest','earliest' - automatically reset the offset to the smallest offset, 'largest','latest' - automatically reset the offset to the largest offset, 'error' - trigger an error (ERR__AUTO_OFFSET_RESET) which is retrieved by consuming messages and checking 'message->err'.
    public enum AutoOffsetReset: String, Sendable {
        case `smallest` = "smallest"
        case `earliest` = "earliest"
        case `beginning` = "beginning"
        case `largest` = "largest"
        case `latest` = "latest"
        case `end` = "end"
        case `error` = "error"
    }
}
