//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-kafka-client open source project
//
// Copyright (c) 2026 Apple Inc. and the swift-kafka-client project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of swift-kafka-client project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################

import struct Foundation.UUID

public struct KafkaConsumerConfig: Sendable {
    // MARK: - Non-librdkafka configuration properties

    /// The time between two consecutive polls.
    /// Effectively controls the rate at which incoming events and messages are consumed.
    /// Default: `.milliseconds(100)`
    public var pollInterval: Duration = .milliseconds(100)

    /// The strategy used for consuming messages.
    public var consumptionStrategy: KafkaConsumerConfiguration.ConsumptionStrategy?

    /// Consumer metrics configuration.
    public var metrics: KafkaConfiguration.ConsumerMetrics = .init()

    // MARK: - Properties generated from librdkafka config list

    /// Client identifier.
    ///
    /// Importance: low
    ///
    /// Default: rdkafka
    public var clientId: String?
    /// Initial list of brokers as a CSV list of broker host or host:port.
    /// The application may also use `rd_kafka_brokers_add()` to add brokers during runtime.
    ///
    /// Importance: high
    public var metadataBrokerList: [String]?
    /// Alias for `metadata.broker.list`: Initial list of brokers as a CSV list of broker host or host:port.
    /// The application may also use `rd_kafka_brokers_add()` to add brokers during runtime.
    ///
    /// Importance: high
    public var bootstrapServers: [String]?
    /// Maximum Kafka protocol request message size.
    /// Due to differing framing overhead between protocol versions the producer is unable to reliably enforce a strict max message limit at produce time and may exceed the maximum size by one message in protocol ProduceRequests, the broker will enforce the the topic's `max.message.bytes` limit (see Apache Kafka documentation).
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 1000000000
    ///
    /// Default: 1000000
    public var messageMaxBytes: Int?
    /// Maximum size for message to be copied to buffer.
    /// Messages larger than this will be passed by reference (zero-copy) at the expense of larger iovecs.
    ///
    /// Importance: low
    ///
    /// Default: 65535
    public var messageCopyMaxBytes: Int?
    /// Maximum Kafka protocol response message size.
    /// This serves as a safety precaution to avoid memory exhaustion in case of protocol hickups.
    /// This value must be at least `fetch.max.bytes`  + 512 to allow for protocol overhead; the value is adjusted automatically unless the configuration property is explicitly set.
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 2147483647
    ///
    /// Default: 100000000
    public var receiveMessageMaxBytes: Int?
    /// Maximum number of in-flight requests per broker connection.
    /// This is a generic property applied to all broker communication, however it is primarily relevant to produce requests.
    /// In particular, note that other mechanisms limit the number of outstanding consumer fetch request per broker to one.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 1000000
    ///
    /// Default: 1000000
    public var maxInFlightRequestsPerConnection: Int?
    /// Alias for `max.in.flight.requests.per.connection`: Maximum number of in-flight requests per broker connection.
    /// This is a generic property applied to all broker communication, however it is primarily relevant to produce requests.
    /// In particular, note that other mechanisms limit the number of outstanding consumer fetch request per broker to one.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 1000000
    ///
    /// Default: 1000000
    public var maxInFlight: Int?
    /// Period of time in milliseconds at which topic and broker metadata is refreshed in order to proactively discover any new brokers, topics, partitions or partition leader changes.
    /// Use -1 to disable the intervalled refresh (not recommended).
    /// If there are no locally referenced topics (no topic objects created, no messages produced, no subscription or no assignment) then only the broker list will be refreshed every interval but no more often than every 10s.
    ///
    /// Importance: low
    ///
    /// Value range: -1 .. 3600000
    ///
    /// Default: 300000
    public var topicMetadataRefreshIntervalMs: Int?
    /// Metadata cache max age.
    /// Defaults to topic.metadata.refresh.interval.ms * 3.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 86400000
    ///
    /// Default: 900000
    public var metadataMaxAgeMs: Int?
    /// When a topic loses its leader a new metadata request will be enqueued immediately and then with this initial interval, exponentially increasing upto `retry.backoff.max.ms`, until the topic metadata has been refreshed.
    /// If not set explicitly, it will be defaulted to `retry.backoff.ms`.
    /// This is used to recover quickly from transitioning leader brokers.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 60000
    ///
    /// Default: 100
    public var topicMetadataRefreshFastIntervalMs: Int?
    /// Sparse metadata requests (consumes less network bandwidth).
    ///
    /// Importance: low
    ///
    /// Default: True
    public var topicMetadataRefreshSparse: Bool?
    /// Apache Kafka topic creation is asynchronous and it takes some time for a new topic to propagate throughout the cluster to all brokers.
    /// If a client requests topic metadata after manual topic creation but before the topic has been fully propagated to the broker the client is requesting metadata from, the topic will seem to be non-existent and the client will mark the topic as such, failing queued produced messages with `ERR__UNKNOWN_TOPIC`.
    /// This setting delays marking a topic as non-existent until the configured propagation max time has passed.
    /// The maximum propagation time is calculated from the time the topic is first referenced in the client, e.g., on produce().
    ///
    /// Importance: low
    ///
    /// Default: 30000
    public var topicMetadataPropagationMaxMs: Int?
    /// Topic ignore list, a comma-separated list of regular expressions for matching topic names that should be ignored in broker metadata information as if the topics did not exist.
    ///
    /// Importance: low
    public var topicIgnorelist: [String]?
    /// A comma-separated list of debug contexts to enable.
    /// Detailed Producer debugging: broker,topic,msg.
    /// Consumer: consumer,cgrp,topic,fetch.
    ///
    /// Importance: medium
    ///
    /// Values: `"generic"`, `"broker"`, `"topic"`, `"metadata"`, `"feature"`, `"queue"`, `"msg"`, `"protocol"`, `"cgrp"`, `"security"`, `"fetch"`, `"interceptor"`, `"plugin"`, `"consumer"`, `"admin"`, `"eos"`, `"mock"`, `"assignor"`, `"conf"`, `"telemetry"`, `"all"`
    public var debug: [KafkaConfig.Debug]?
    /// Default timeout for network requests.
    /// Producer: ProduceRequests will use the lesser value of `socket.timeout.ms` and remaining `message.timeout.ms` for the first message in the batch.
    /// Consumer: FetchRequests will use `fetch.wait.max.ms` + `socket.timeout.ms`.
    /// Admin: Admin requests will use `socket.timeout.ms` or explicitly set `rd_kafka_AdminOptions_set_operation_timeout()` value.
    ///
    /// Importance: low
    ///
    /// Value range: 10 .. 300000
    ///
    /// Default: 60000
    public var socketTimeoutMs: Int?
    /// Broker socket send buffer size.
    /// System default is used if 0.
    ///
    /// Importance: low
    public var socketSendBufferBytes: Int?
    /// Broker socket receive buffer size.
    /// System default is used if 0.
    ///
    /// Importance: low
    public var socketReceiveBufferBytes: Int?
    /// Enable TCP keep-alives (SO_KEEPALIVE) on broker sockets.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var socketKeepaliveEnable: Bool?
    /// Disable the Nagle algorithm (TCP_NODELAY) on broker sockets.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var socketNagleDisable: Bool?
    /// Disconnect from broker when this number of send failures (e.g., timed out requests) is reached.
    /// Disable with 0.
    /// WARNING: It is highly recommended to leave this setting at its default value of 1 to avoid the client and broker to become desynchronized in case of request timeouts.
    /// NOTE: The connection is automatically re-established.
    ///
    /// Importance: low
    ///
    /// Default: 1
    public var socketMaxFails: Int?
    /// How long to cache the broker address resolving results (milliseconds).
    ///
    /// Importance: low
    ///
    /// Default: 1000
    public var brokerAddressTtl: Int?
    /// Allowed broker IP address families: any, v4, v6.
    ///
    /// Importance: low
    ///
    /// Values: `"any"`, `"v4"`, `"v6"`
    ///
    /// Default: any
    public var brokerAddressFamily: KafkaConfig.BrokerAddressFamily?
    /// Maximum time allowed for broker connection setup (TCP connection setup as well SSL and SASL handshake).
    /// If the connection to the broker is not fully functional after this the connection will be closed and retried.
    ///
    /// Importance: medium
    ///
    /// Value range: 1000 .. 2147483647
    ///
    /// Default: 30000
    public var socketConnectionSetupTimeoutMs: Int?
    /// Close broker connections after the specified time of inactivity.
    /// Disable with 0.
    /// If this property is left at its default value some heuristics are performed to determine a suitable default value, this is currently limited to identifying brokers on Azure (see librdkafka issue #3109 for more info).
    ///
    /// Importance: medium
    public var connectionsMaxIdleMs: Int?
    /// The initial time to wait before reconnecting to a broker after the connection has been closed.
    /// The time is increased exponentially until `reconnect.backoff.max.ms` is reached.
    /// -25% to +50% jitter is applied to each reconnect backoff.
    /// A value of 0 disables the backoff and reconnects immediately.
    ///
    /// Importance: medium
    ///
    /// Default: 100
    public var reconnectBackoffMs: Int?
    /// The maximum time to wait before reconnecting to a broker after the connection has been closed.
    ///
    /// Importance: medium
    ///
    /// Default: 10000
    public var reconnectBackoffMaxMs: Int?
    /// librdkafka statistics emit interval.
    /// The application also needs to register a stats callback using `rd_kafka_conf_set_stats_cb()`.
    /// The granularity is 1000ms.
    /// A value of 0 disables statistics.
    ///
    /// Importance: high
    public var statisticsIntervalMs: Int?
    /// See `rd_kafka_conf_set_events()`.
    ///
    /// Importance: low
    public var enabled_events: Int?
    /// Logging level (syslog(3) levels).
    ///
    /// Importance: low
    ///
    /// Default: 6
    public var log_level: Int?
    /// Disable spontaneous log_cb from internal librdkafka threads, instead enqueue log messages on queue set with `rd_kafka_set_log_queue()` and serve log callbacks or events through the standard poll APIs.
    /// **NOTE**: Log messages will linger in a temporary queue until the log queue has been set.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var logQueue: Bool?
    /// Print internal thread name in log messages (useful for debugging librdkafka internals).
    ///
    /// Importance: low
    ///
    /// Default: True
    public var logThreadName: Bool?
    /// If enabled librdkafka will initialize the PRNG with srand(current_time.milliseconds) on the first invocation of rd_kafka_new() (required only if rand_r() is not available on your platform).
    /// If disabled the application must call srand() prior to calling rd_kafka_new().
    ///
    /// Importance: low
    ///
    /// Default: True
    public var enableRandomSeed: Bool?
    /// Log broker disconnects.
    /// It might be useful to turn this off when interacting with 0.9 brokers with an aggressive `connections.max.idle.ms` value.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var logConnectionClose: Bool?
    /// Signal that librdkafka will use to quickly terminate on rd_kafka_destroy().
    /// If this signal is not set then there will be a delay before rd_kafka_wait_destroyed() returns true as internal threads are timing out their system calls.
    /// If this signal is set however the delay will be minimal.
    /// The application should mask this signal as an internal signal handler is installed.
    ///
    /// Importance: low
    public var internalTerminationSignal: Int?
    /// Request broker's supported API versions to adjust functionality to available protocol features.
    /// If set to false, or the ApiVersionRequest fails, the fallback version `broker.version.fallback` will be used.
    /// **NOTE**: Depends on broker version >=0.10.0.
    /// If the request is not supported by (an older) broker the `broker.version.fallback` fallback is used.
    ///
    /// Importance: high
    ///
    /// Default: True
    public var apiVersionRequest: Bool?
    /// Timeout for broker API version requests.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 300000
    ///
    /// Default: 10000
    public var apiVersionRequestTimeoutMs: Int?
    /// Dictates how long the `broker.version.fallback` fallback is used in the case the ApiVersionRequest fails.
    /// **NOTE**: The ApiVersionRequest is only issued when a new connection to the broker is made (such as after an upgrade).
    ///
    /// Importance: medium
    public var apiVersionFallbackMs: Int?
    /// Older broker versions (before 0.10.0) provide no way for a client to query for supported protocol features (ApiVersionRequest, see `api.version.request`) making it impossible for the client to know what features it may use.
    /// As a workaround a user may set this property to the expected broker version and the client will automatically adjust its feature set accordingly if the ApiVersionRequest fails (or is disabled).
    /// The fallback broker version will be used for `api.version.fallback.ms`.
    /// Valid values are: 0.9.0, 0.8.2, 0.8.1, 0.8.0.
    /// Any other value >= 0.10, such as 0.10.2.1, enables ApiVersionRequests.
    ///
    /// Importance: medium
    ///
    /// Default: 0.10.0
    public var brokerVersionFallback: String?
    /// Allow automatic topic creation on the broker when subscribing to or assigning non-existent topics.
    /// The broker must also be configured with `auto.create.topics.enable=true` for this configuration to take effect.
    /// Note: the default value (true) for the producer is different from the default value (false) for the consumer.
    /// Further, the consumer default value is different from the Java consumer (true), and this property is not supported by the Java producer.
    /// Requires broker version >= 0.11.0.0, for older broker versions only the broker configuration applies.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var allowAutoCreateTopics: Bool?
    /// Protocol used to communicate with brokers.
    ///
    /// Importance: high
    ///
    /// Values: `"plaintext"`, `"ssl"`, `"sasl_plaintext"`, `"sasl_ssl"`
    ///
    /// Default: plaintext
    public var securityProtocol: KafkaConfig.SecurityProtocol?
    /// A cipher suite is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol.
    /// See manual page for `ciphers(1)` and `SSL_CTX_set_cipher_list(3).
    ///
    /// Importance: low
    public var sslCipherSuites: String?
    /// The supported-curves extension in the TLS ClientHello message specifies the curves (standard/named, or 'explicit' GF(2^k) or GF(p)) the client is willing to have the server use.
    /// See manual page for `SSL_CTX_set1_curves_list(3)`.
    /// OpenSSL >= 1.0.2 required.
    ///
    /// Importance: low
    public var sslCurvesList: String?
    /// The client uses the TLS ClientHello signature_algorithms extension to indicate to the server which signature/hash algorithm pairs may be used in digital signatures.
    /// See manual page for `SSL_CTX_set1_sigalgs_list(3)`.
    /// OpenSSL >= 1.0.2 required.
    ///
    /// Importance: low
    public var sslSigalgsList: String?
    /// Path to client's private key (PEM) used for authentication.
    ///
    /// Importance: low
    public var sslKeyLocation: String?
    /// Private key passphrase (for use with `ssl.key.location` and `set_ssl_cert()`).
    ///
    /// Importance: low
    public var sslKeyPassword: String?
    /// Client's private key string (PEM format) used for authentication.
    ///
    /// Importance: low
    public var sslKeyPem: String?
    /// Path to client's public key (PEM) used for authentication.
    ///
    /// Importance: low
    public var sslCertificateLocation: String?
    /// Client's public key string (PEM format) used for authentication.
    ///
    /// Importance: low
    public var sslCertificatePem: String?
    /// File or directory path to CA certificate(s) for verifying the broker's key.
    /// Defaults: On Windows the system's CA certificates are automatically looked up in the Windows Root certificate store.
    /// On Mac OSX this configuration defaults to `probe`.
    /// It is recommended to install openssl using Homebrew, to provide CA certificates.
    /// On Linux install the distribution's ca-certificates package.
    /// If OpenSSL is statically linked or `ssl.ca.location` is set to `probe` a list of standard paths will be probed and the first one found will be used as the default CA certificate location path.
    /// If OpenSSL is dynamically linked the OpenSSL library's default path will be used (see `OPENSSLDIR` in `openssl version -a`).
    ///
    /// Importance: low
    public var sslCaLocation: String?
    /// CA certificate string (PEM format) for verifying the broker's key.
    ///
    /// Importance: low
    public var sslCaPem: String?
    /// Comma-separated list of Windows Certificate stores to load CA certificates from.
    /// Certificates will be loaded in the same order as stores are specified.
    /// If no certificates can be loaded from any of the specified stores an error is logged and the OpenSSL library's default CA location is used instead.
    /// Store names are typically one or more of: MY, Root, Trust, CA.
    ///
    /// Importance: low
    ///
    /// Default: Root
    public var sslCaCertificateStores: String?
    /// Path to CRL for verifying broker's certificate validity.
    ///
    /// Importance: low
    public var sslCrlLocation: String?
    /// Path to client's keystore (PKCS#12) used for authentication.
    ///
    /// Importance: low
    public var sslKeystoreLocation: String?
    /// Client's keystore (PKCS#12) password.
    ///
    /// Importance: low
    public var sslKeystorePassword: String?
    /// Comma-separated list of OpenSSL 3.0.x implementation providers.
    /// E.g., "default,legacy".
    ///
    /// Importance: low
    public var sslProviders: String?
    /// OpenSSL engine id is the name used for loading engine.
    ///
    /// Importance: low
    ///
    /// Default: dynamic
    public var sslEngineId: String?
    /// Enable OpenSSL's builtin broker (server) certificate verification.
    /// This verification can be extended by the application by implementing a certificate_verify_cb.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var enableSslCertificateVerification: Bool?
    /// Endpoint identification algorithm to validate broker hostname using broker certificate.
    /// https - Server (broker) hostname verification as specified in RFC2818.
    /// none - No endpoint verification.
    /// OpenSSL >= 1.0.2 required.
    ///
    /// Importance: low
    ///
    /// Values: `"none"`, `"https"`
    ///
    /// Default: https
    public var sslEndpointIdentificationAlgorithm: KafkaConfig.SslEndpointIdentificationAlgorithm?
    /// SASL mechanism to use for authentication.
    /// Supported: GSSAPI, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, OAUTHBEARER.
    /// **NOTE**: Despite the name only one mechanism must be configured.
    ///
    /// Importance: high
    ///
    /// Default: GSSAPI
    public var saslMechanisms: String?
    /// Alias for `sasl.mechanisms`: SASL mechanism to use for authentication.
    /// Supported: GSSAPI, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, OAUTHBEARER.
    /// **NOTE**: Despite the name only one mechanism must be configured.
    ///
    /// Importance: high
    ///
    /// Default: GSSAPI
    public var saslMechanism: String?
    /// Kerberos principal name that Kafka runs as, not including /hostname@REALM.
    ///
    /// Importance: low
    ///
    /// Default: kafka
    public var saslKerberosServiceName: String?
    /// This client's Kerberos principal name.
    /// (Not supported on Windows, will use the logon user's principal).
    ///
    /// Importance: low
    ///
    /// Default: kafkaclient
    public var saslKerberosPrincipal: String?
    /// Shell command to refresh or acquire the client's Kerberos ticket.
    /// This command is executed on client creation and every sasl.kerberos.min.time.before.relogin (0=disable).
    /// %{config.prop.name} is replaced by corresponding config object value.
    ///
    /// Importance: low
    ///
    /// Default: kinit -R -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal} \|\| kinit -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal}
    public var saslKerberosKinitCmd: String?
    /// Path to Kerberos keytab file.
    /// This configuration property is only used as a variable in `sasl.kerberos.kinit.cmd` as ` ..
    /// -t "%{sasl.kerberos.keytab}"`.
    ///
    /// Importance: low
    public var saslKerberosKeytab: String?
    /// Minimum time in milliseconds between key refresh attempts.
    /// Disable automatic key refresh by setting this property to 0.
    ///
    /// Importance: low
    ///
    /// Default: 60000
    public var saslKerberosMinTimeBeforeRelogin: Int?
    /// SASL username for use with the PLAIN and SASL-SCRAM-.
    /// mechanisms.
    ///
    /// Importance: high
    public var saslUsername: String?
    /// SASL password for use with the PLAIN and SASL-SCRAM-.
    /// mechanism.
    ///
    /// Importance: high
    public var saslPassword: String?
    /// SASL/OAUTHBEARER configuration.
    /// The format is implementation-dependent and must be parsed accordingly.
    /// The default unsecured token implementation (see https://tools.ietf.org/html/rfc7515#appendix-A.5) recognizes space-separated name=value pairs with valid names including principalClaimName, principal, scopeClaimName, scope, and lifeSeconds.
    /// The default value for principalClaimName is "sub", the default value for scopeClaimName is "scope", and the default value for lifeSeconds is 3600.
    /// The scope value is CSV format with the default value being no/empty scope.
    /// For example: `principalClaimName=azp principal=admin scopeClaimName=roles scope=role1,role2 lifeSeconds=600`.
    /// In addition, SASL extensions can be communicated to the broker via `extension_NAME=value`.
    /// For example: `principal=admin extension_traceId=123`.
    ///
    /// Importance: low
    public var saslOauthbearerConfig: String?
    /// Enable the builtin unsecure JWT OAUTHBEARER token handler if no oauthbearer_refresh_cb has been set.
    /// This builtin handler should only be used for development or testing, and not in production.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var enableSaslOauthbearerUnsecureJwt: Bool?
    /// Set to "default" or "oidc" to control which login method to be used.
    /// If set to "oidc", the following properties must also be be specified: `sasl.oauthbearer.client.id`, `sasl.oauthbearer.client.secret`, and `sasl.oauthbearer.token.endpoint.url`.
    ///
    /// Importance: low
    ///
    /// Values: `"default"`, `"oidc"`
    ///
    /// Default: default
    public var saslOauthbearerMethod: KafkaConfig.SaslOauthbearerMethod?
    /// Public identifier for the application.
    /// Must be unique across all clients that the authorization server handles.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    public var saslOauthbearerClientId: String?
    /// Client secret only known to the application and the authorization server.
    /// This should be a sufficiently random string that is not guessable.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    public var saslOauthbearerClientSecret: String?
    /// Client use this to specify the scope of the access request to the broker.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    public var saslOauthbearerScope: String?
    /// Allow additional information to be provided to the broker.
    /// Comma-separated list of key=value pairs.
    /// E.g., "supportFeatureX=true,organizationId=sales-emea".Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    public var saslOauthbearerExtensions: String?
    /// OAuth/OIDC issuer token endpoint HTTP(S) URI used to retrieve token.
    /// Only used when `sasl.oauthbearer.method` is set to "oidc".
    ///
    /// Importance: low
    public var saslOauthbearerTokenEndpointUrl: String?
    /// List of plugin libraries to load (; separated).
    /// The library search path is platform dependent (see dlopen(3) for Unix and LoadLibrary() for Windows).
    /// If no filename extension is specified the platform-specific extension (such as .dll or .so) will be appended automatically.
    ///
    /// Importance: low
    public var pluginLibraryPaths: String?
    /// Client group id string.
    /// All clients sharing the same group.id belong to the same group.
    ///
    /// Importance: high
    public var groupId: String?
    /// Enable static group membership.
    /// Static group members are able to leave and rejoin a group within the configured `session.timeout.ms` without prompting a group rebalance.
    /// This should be used in combination with a larger `session.timeout.ms` to avoid group rebalances caused by transient unavailability (e.g.
    /// process restarts).
    /// Requires broker version >= 2.3.0.
    ///
    /// Importance: medium
    public var groupInstanceId: String?
    /// The name of one or more partition assignment strategies.
    /// The elected group leader will use a strategy supported by all members of the group to assign partitions to group members.
    /// If there is more than one eligible strategy, preference is determined by the order of this list (strategies earlier in the list have higher priority).
    /// Cooperative and non-cooperative (eager) strategies must not be mixed.
    /// Available strategies: range, roundrobin, cooperative-sticky.
    ///
    /// Importance: medium
    ///
    /// Default: range,roundrobin
    public var partitionAssignmentStrategy: String?
    /// Client group session and failure detection timeout.
    /// The consumer sends periodic heartbeats (heartbeat.interval.ms) to indicate its liveness to the broker.
    /// If no hearts are received by the broker for a group member within the session timeout, the broker will remove the consumer from the group and trigger a rebalance.
    /// The allowed range is configured with the **broker** configuration properties `group.min.session.timeout.ms` and `group.max.session.timeout.ms`.
    /// Also see `max.poll.interval.ms`.
    ///
    /// Importance: high
    ///
    /// Value range: 1 .. 3600000
    ///
    /// Default: 45000
    public var sessionTimeoutMs: Int?
    /// Group session keepalive heartbeat interval.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 3600000
    ///
    /// Default: 3000
    public var heartbeatIntervalMs: Int?
    /// Group protocol type for the `classic` group protocol.
    /// NOTE: Currently, the only supported group protocol type is `consumer`.
    ///
    /// Importance: low
    ///
    /// Default: consumer
    public var groupProtocolType: String?
    /// Group protocol to use.
    /// Use `classic` for the original protocol and `consumer` for the new protocol introduced in KIP-848.
    /// Available protocols: classic or consumer.
    /// Default is `classic`, but will change to `consumer` in next releases.
    ///
    /// Importance: high
    ///
    /// Values: `"classic"`, `"consumer"`
    ///
    /// Default: classic
    public var groupProtocol: KafkaConfig.GroupProtocol?
    /// Server side assignor to use.
    /// Keep it null to make server select a suitable assignor for the group.
    /// Available assignors: uniform or range.
    /// Default is null.
    ///
    /// Importance: medium
    public var groupRemoteAssignor: String?
    /// How often to query for the current client group coordinator.
    /// If the currently assigned coordinator is down the configured query interval will be divided by ten to more quickly recover in case of coordinator reassignment.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 3600000
    ///
    /// Default: 600000
    public var coordinatorQueryIntervalMs: Int?
    /// Maximum allowed time between calls to consume messages (e.g., rd_kafka_consumer_poll()) for high-level consumers.
    /// If this interval is exceeded the consumer is considered failed and the group will rebalance in order to reassign the partitions to another consumer group member.
    /// Warning: Offset commits may be not possible at this point.
    /// Note: It is recommended to set `enable.auto.offset.store=false` for long-time processing applications and then explicitly store offsets (using offsets_store()) *after* message processing, to make sure offsets are not auto-committed prior to processing has finished.
    /// The interval is checked two times per second.
    /// See KIP-62 for more information.
    ///
    /// Importance: high
    ///
    /// Value range: 1 .. 86400000
    ///
    /// Default: 300000
    public var maxPollIntervalMs: Int?
    /// Automatically and periodically commit offsets in the background.
    /// Note: setting this to false does not prevent the consumer from fetching previously committed start offsets.
    /// To circumvent this behaviour set specific start offsets per partition in the call to assign().
    ///
    /// Importance: high
    ///
    /// Default: True
    public var enableAutoCommit: Bool?
    /// The frequency in milliseconds that the consumer offsets are committed (written) to offset storage.
    /// (0 = disable).
    /// This setting is used by the high-level consumer.
    ///
    /// Importance: medium
    ///
    /// Default: 5000
    public var autoCommitIntervalMs: Int?
    /// Automatically store offset of last message provided to application.
    /// The offset store is an in-memory store of the next offset to (auto-)commit for each partition.
    ///
    /// Importance: high
    ///
    /// Default: True
    public var enableAutoOffsetStore: Bool?
    /// Minimum number of messages per topic+partition librdkafka tries to maintain in the local consumer queue.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 10000000
    ///
    /// Default: 100000
    public var queuedMinMessages: Int?
    /// Maximum number of kilobytes of queued pre-fetched messages in the local consumer queue.
    /// If using the high-level consumer this setting applies to the single consumer queue, regardless of the number of partitions.
    /// When using the legacy simple consumer or when separate partition queues are used this setting applies per partition.
    /// This value may be overshot by fetch.message.max.bytes.
    /// This property has higher priority than queued.min.messages.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 2097151
    ///
    /// Default: 65536
    public var queuedMaxMessagesKbytes: Int?
    /// Maximum time the broker may wait to fill the Fetch response with fetch.min.bytes of messages.
    ///
    /// Importance: low
    ///
    /// Default: 500
    public var fetchWaitMaxMs: Int?
    /// How long to postpone the next fetch request for a topic+partition in case the current fetch queue thresholds (queued.min.messages or queued.max.messages.kbytes) have been exceded.
    /// This property may need to be decreased if the queue thresholds are set low and the application is experiencing long (~1s) delays between messages.
    /// Low values may increase CPU utilization.
    ///
    /// Importance: medium
    ///
    /// Default: 1000
    public var fetchQueueBackoffMs: Int?
    /// Initial maximum number of bytes per topic+partition to request when fetching messages from the broker.
    /// If the client encounters a message larger than this value it will gradually try to increase it until the entire message can be fetched.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 1000000000
    ///
    /// Default: 1048576
    public var fetchMessageMaxBytes: Int?
    /// Alias for `fetch.message.max.bytes`: Initial maximum number of bytes per topic+partition to request when fetching messages from the broker.
    /// If the client encounters a message larger than this value it will gradually try to increase it until the entire message can be fetched.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 1000000000
    ///
    /// Default: 1048576
    public var maxPartitionFetchBytes: Int?
    /// Maximum amount of data the broker shall return for a Fetch request.
    /// Messages are fetched in batches by the consumer and if the first message batch in the first non-empty partition of the Fetch request is larger than this value, then the message batch will still be returned to ensure the consumer can make progress.
    /// The maximum message batch size accepted by the broker is defined via `message.max.bytes` (broker config) or `max.message.bytes` (broker topic config).
    /// `fetch.max.bytes` is automatically adjusted upwards to be at least `message.max.bytes` (consumer config).
    ///
    /// Importance: medium
    ///
    /// Default: 52428800
    public var fetchMaxBytes: Int?
    /// Minimum number of bytes the broker responds with.
    /// If fetch.wait.max.ms expires the accumulated data will be sent to the client regardless of this setting.
    ///
    /// Importance: low
    ///
    /// Value range: 1 .. 100000000
    ///
    /// Default: 1
    public var fetchMinBytes: Int?
    /// How long to postpone the next fetch request for a topic+partition in case of a fetch error.
    ///
    /// Importance: medium
    ///
    /// Default: 500
    public var fetchErrorBackoffMs: Int?
    /// Controls how to read messages written transactionally: `read_committed` - only return transactional messages which have been committed.
    /// `read_uncommitted` - return all messages, even transactional messages which have been aborted.
    ///
    /// Importance: high
    ///
    /// Values: `"read_uncommitted"`, `"read_committed"`
    ///
    /// Default: read_committed
    public var isolationLevel: KafkaConfig.IsolationLevel?
    /// Emit RD_KAFKA_RESP_ERR__PARTITION_EOF event whenever the consumer reaches the end of a partition.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var enablePartitionEof: Bool?
    /// Verify CRC32 of consumed messages, ensuring no on-the-wire or on-disk corruption to the messages occurred.
    /// This check comes at slightly increased CPU usage.
    ///
    /// Importance: medium
    ///
    /// Default: True
    public var checkCrcs: Bool?
    /// A rack identifier for this client.
    /// This can be any string value which indicates where this client is physically located.
    /// It corresponds with the broker config `broker.rack`.
    ///
    /// Importance: low
    public var clientRack: String?
    /// The backoff time in milliseconds before retrying a protocol request, this is the first backoff time, and will be backed off exponentially until number of retries is exhausted, and it's capped by retry.backoff.max.ms.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 300000
    ///
    /// Default: 100
    public var retryBackoffMs: Int?
    /// The max backoff time in milliseconds before retrying a protocol request, this is the atmost backoff allowed for exponentially backed off requests.
    ///
    /// Importance: medium
    ///
    /// Value range: 1 .. 300000
    ///
    /// Default: 1000
    public var retryBackoffMaxMs: Int?
    /// Controls how the client uses DNS lookups.
    /// By default, when the lookup returns multiple IP addresses for a hostname, they will all be attempted for connection before the connection is considered failed.
    /// This applies to both bootstrap and advertised servers.
    /// If the value is set to `resolve_canonical_bootstrap_servers_only`, each entry will be resolved and expanded into a list of canonical names.
    /// **WARNING**: `resolve_canonical_bootstrap_servers_only` must only be used with `GSSAPI` (Kerberos) as `sasl.mechanism`, as it's the only purpose of this configuration value.
    /// **NOTE**: Default here is different from the Java client's default behavior, which connects only to the first IP address returned for a hostname.
    ///
    /// Importance: low
    ///
    /// Values: `"use_all_dns_ips"`, `"resolve_canonical_bootstrap_servers_only"`
    ///
    /// Default: use_all_dns_ips
    public var clientDnsLookup: KafkaConfig.ClientDnsLookup?
    /// Whether to enable pushing of client metrics to the cluster, if the cluster has a client metrics subscription which matches this client.
    ///
    /// Importance: low
    ///
    /// Default: True
    public var enableMetricsPush: Bool?
    /// Action to take when there is no initial offset in offset store or the desired offset is out of range: 'smallest','earliest' - automatically reset the offset to the smallest offset, 'largest','latest' - automatically reset the offset to the largest offset, 'error' - trigger an error (ERR__AUTO_OFFSET_RESET) which is retrieved by consuming messages and checking 'message->err'.
    ///
    /// Importance: high
    ///
    /// Values: `"smallest"`, `"earliest"`, `"beginning"`, `"largest"`, `"latest"`, `"end"`, `"error"`
    ///
    /// Default: largest
    public var autoOffsetReset: KafkaConfig.AutoOffsetReset?
    /// Maximum number of messages to dispatch in one `rd_kafka_consume_callback*()` call (0 = unlimited).
    ///
    /// Importance: low
    public var consumeCallbackMaxMessages: Int?

    public init() {}

    internal var config: [String: String] {
        var config: [String: String] = [:]

        config["client.id"] = self.clientId?.description
        config["metadata.broker.list"] = self.metadataBrokerList?.joined(separator: ",")
        config["bootstrap.servers"] = self.bootstrapServers?.joined(separator: ",")
        config["message.max.bytes"] = self.messageMaxBytes?.description
        config["message.copy.max.bytes"] = self.messageCopyMaxBytes?.description
        config["receive.message.max.bytes"] = self.receiveMessageMaxBytes?.description
        config["max.in.flight.requests.per.connection"] = self.maxInFlightRequestsPerConnection?.description
        config["max.in.flight"] = self.maxInFlight?.description
        config["topic.metadata.refresh.interval.ms"] = self.topicMetadataRefreshIntervalMs?.description
        config["metadata.max.age.ms"] = self.metadataMaxAgeMs?.description
        config["topic.metadata.refresh.fast.interval.ms"] = self.topicMetadataRefreshFastIntervalMs?.description
        config["topic.metadata.refresh.sparse"] = self.topicMetadataRefreshSparse?.description
        config["topic.metadata.propagation.max.ms"] = self.topicMetadataPropagationMaxMs?.description
        config["topic.blacklist"] = self.topicIgnorelist?.joined(separator: ",")  // ignore-unacceptable-language
        config["debug"] = self.debug?.map(\.rawValue).joined(separator: ",")
        config["socket.timeout.ms"] = self.socketTimeoutMs?.description
        config["socket.send.buffer.bytes"] = self.socketSendBufferBytes?.description
        config["socket.receive.buffer.bytes"] = self.socketReceiveBufferBytes?.description
        config["socket.keepalive.enable"] = self.socketKeepaliveEnable?.description
        config["socket.nagle.disable"] = self.socketNagleDisable?.description
        config["socket.max.fails"] = self.socketMaxFails?.description
        config["broker.address.ttl"] = self.brokerAddressTtl?.description
        config["broker.address.family"] = self.brokerAddressFamily?.rawValue
        config["socket.connection.setup.timeout.ms"] = self.socketConnectionSetupTimeoutMs?.description
        config["connections.max.idle.ms"] = self.connectionsMaxIdleMs?.description
        config["reconnect.backoff.ms"] = self.reconnectBackoffMs?.description
        config["reconnect.backoff.max.ms"] = self.reconnectBackoffMaxMs?.description
        config["statistics.interval.ms"] = self.statisticsIntervalMs?.description
        config["enabled_events"] = self.enabled_events?.description
        config["log_level"] = self.log_level?.description
        config["log.queue"] = self.logQueue?.description
        config["log.thread.name"] = self.logThreadName?.description
        config["enable.random.seed"] = self.enableRandomSeed?.description
        config["log.connection.close"] = self.logConnectionClose?.description
        config["internal.termination.signal"] = self.internalTerminationSignal?.description
        config["api.version.request"] = self.apiVersionRequest?.description
        config["api.version.request.timeout.ms"] = self.apiVersionRequestTimeoutMs?.description
        config["api.version.fallback.ms"] = self.apiVersionFallbackMs?.description
        config["broker.version.fallback"] = self.brokerVersionFallback?.description
        config["allow.auto.create.topics"] = self.allowAutoCreateTopics?.description
        config["security.protocol"] = self.securityProtocol?.rawValue
        config["ssl.cipher.suites"] = self.sslCipherSuites?.description
        config["ssl.curves.list"] = self.sslCurvesList?.description
        config["ssl.sigalgs.list"] = self.sslSigalgsList?.description
        config["ssl.key.location"] = self.sslKeyLocation?.description
        config["ssl.key.password"] = self.sslKeyPassword?.description
        config["ssl.key.pem"] = self.sslKeyPem?.description
        config["ssl.certificate.location"] = self.sslCertificateLocation?.description
        config["ssl.certificate.pem"] = self.sslCertificatePem?.description
        config["ssl.ca.location"] = self.sslCaLocation?.description
        config["ssl.ca.pem"] = self.sslCaPem?.description
        config["ssl.ca.certificate.stores"] = self.sslCaCertificateStores?.description
        config["ssl.crl.location"] = self.sslCrlLocation?.description
        config["ssl.keystore.location"] = self.sslKeystoreLocation?.description
        config["ssl.keystore.password"] = self.sslKeystorePassword?.description
        config["ssl.providers"] = self.sslProviders?.description
        config["ssl.engine.id"] = self.sslEngineId?.description
        config["enable.ssl.certificate.verification"] = self.enableSslCertificateVerification?.description
        config["ssl.endpoint.identification.algorithm"] = self.sslEndpointIdentificationAlgorithm?.rawValue
        config["sasl.mechanisms"] = self.saslMechanisms?.description
        config["sasl.mechanism"] = self.saslMechanism?.description
        config["sasl.kerberos.service.name"] = self.saslKerberosServiceName?.description
        config["sasl.kerberos.principal"] = self.saslKerberosPrincipal?.description
        config["sasl.kerberos.kinit.cmd"] = self.saslKerberosKinitCmd?.description
        config["sasl.kerberos.keytab"] = self.saslKerberosKeytab?.description
        config["sasl.kerberos.min.time.before.relogin"] = self.saslKerberosMinTimeBeforeRelogin?.description
        config["sasl.username"] = self.saslUsername?.description
        config["sasl.password"] = self.saslPassword?.description
        config["sasl.oauthbearer.config"] = self.saslOauthbearerConfig?.description
        config["enable.sasl.oauthbearer.unsecure.jwt"] = self.enableSaslOauthbearerUnsecureJwt?.description
        config["sasl.oauthbearer.method"] = self.saslOauthbearerMethod?.rawValue
        config["sasl.oauthbearer.client.id"] = self.saslOauthbearerClientId?.description
        config["sasl.oauthbearer.client.secret"] = self.saslOauthbearerClientSecret?.description
        config["sasl.oauthbearer.scope"] = self.saslOauthbearerScope?.description
        config["sasl.oauthbearer.extensions"] = self.saslOauthbearerExtensions?.description
        config["sasl.oauthbearer.token.endpoint.url"] = self.saslOauthbearerTokenEndpointUrl?.description
        config["plugin.library.paths"] = self.pluginLibraryPaths?.description
        config["group.id"] = self.groupId?.description
        config["group.instance.id"] = self.groupInstanceId?.description
        config["partition.assignment.strategy"] = self.partitionAssignmentStrategy?.description
        config["session.timeout.ms"] = self.sessionTimeoutMs?.description
        config["heartbeat.interval.ms"] = self.heartbeatIntervalMs?.description
        config["group.protocol.type"] = self.groupProtocolType?.description
        config["group.protocol"] = self.groupProtocol?.rawValue
        config["group.remote.assignor"] = self.groupRemoteAssignor?.description
        config["coordinator.query.interval.ms"] = self.coordinatorQueryIntervalMs?.description
        config["max.poll.interval.ms"] = self.maxPollIntervalMs?.description
        config["enable.auto.commit"] = self.enableAutoCommit?.description
        config["auto.commit.interval.ms"] = self.autoCommitIntervalMs?.description
        config["enable.auto.offset.store"] = self.enableAutoOffsetStore?.description
        config["queued.min.messages"] = self.queuedMinMessages?.description
        config["queued.max.messages.kbytes"] = self.queuedMaxMessagesKbytes?.description
        config["fetch.wait.max.ms"] = self.fetchWaitMaxMs?.description
        config["fetch.queue.backoff.ms"] = self.fetchQueueBackoffMs?.description
        config["fetch.message.max.bytes"] = self.fetchMessageMaxBytes?.description
        config["max.partition.fetch.bytes"] = self.maxPartitionFetchBytes?.description
        config["fetch.max.bytes"] = self.fetchMaxBytes?.description
        config["fetch.min.bytes"] = self.fetchMinBytes?.description
        config["fetch.error.backoff.ms"] = self.fetchErrorBackoffMs?.description
        config["isolation.level"] = self.isolationLevel?.rawValue
        config["enable.partition.eof"] = self.enablePartitionEof?.description
        config["check.crcs"] = self.checkCrcs?.description
        config["client.rack"] = self.clientRack?.description
        config["retry.backoff.ms"] = self.retryBackoffMs?.description
        config["retry.backoff.max.ms"] = self.retryBackoffMaxMs?.description
        config["client.dns.lookup"] = self.clientDnsLookup?.rawValue
        config["enable.metrics.push"] = self.enableMetricsPush?.description
        config["auto.offset.reset"] = self.autoOffsetReset?.rawValue
        config["consume.callback.max.messages"] = self.consumeCallbackMaxMessages?.description

        if config["group.id"] == nil, let consumptionStrategy = self.consumptionStrategy?._internal {
            switch consumptionStrategy {
            case .partition(let groupID, _, _, _):
                if let groupID {
                    config["group.id"] = groupID
                } else {
                    // Although an assignment is not related to a consumer group,
                    // librdkafka requires us to set a `group.id`.
                    // This is a known issue:
                    // https://github.com/edenhill/librdkafka/issues/3261
                    config["group.id"] = UUID().uuidString
                }
            case .group(let groupID, _):
                config["group.id"] = groupID
            }
        }

        if config["statistics.interval.ms"] == nil,
            metrics.enabled,
            let updateInterval = metrics.updateInterval
        {
            config["statistics.interval.ms"] = String(updateInterval.inMilliseconds)
        }

        return config
    }

    // swift-format-ignore
    internal init(_ configDict: [String: String]) {
        self.clientId = configDict["client.id"]
        self.metadataBrokerList = configDict["metadata.broker.list"]?.components(separatedBy: ",")
        self.bootstrapServers = configDict["bootstrap.servers"]?.components(separatedBy: ",")
        self.messageMaxBytes = Int(configDict["message.max.bytes"] ?? "")
        self.messageCopyMaxBytes = Int(configDict["message.copy.max.bytes"] ?? "")
        self.receiveMessageMaxBytes = Int(configDict["receive.message.max.bytes"] ?? "")
        self.maxInFlightRequestsPerConnection = Int(configDict["max.in.flight.requests.per.connection"] ?? "")
        self.maxInFlight = Int(configDict["max.in.flight"] ?? "")
        self.topicMetadataRefreshIntervalMs = Int(configDict["topic.metadata.refresh.interval.ms"] ?? "")
        self.metadataMaxAgeMs = Int(configDict["metadata.max.age.ms"] ?? "")
        self.topicMetadataRefreshFastIntervalMs = Int(configDict["topic.metadata.refresh.fast.interval.ms"] ?? "")
        self.topicMetadataRefreshSparse = Bool(configDict["topic.metadata.refresh.sparse"] ?? "")
        self.topicMetadataPropagationMaxMs = Int(configDict["topic.metadata.propagation.max.ms"] ?? "")
        self.topicIgnorelist = configDict["topic.blacklist"]?.components(separatedBy: ",") // ignore-unacceptable-language
        self.debug = configDict["debug"]?.components(separatedBy: ",").map { KafkaConfig.Debug(rawValue: $0)! }
        self.socketTimeoutMs = Int(configDict["socket.timeout.ms"] ?? "")
        self.socketSendBufferBytes = Int(configDict["socket.send.buffer.bytes"] ?? "")
        self.socketReceiveBufferBytes = Int(configDict["socket.receive.buffer.bytes"] ?? "")
        self.socketKeepaliveEnable = Bool(configDict["socket.keepalive.enable"] ?? "")
        self.socketNagleDisable = Bool(configDict["socket.nagle.disable"] ?? "")
        self.socketMaxFails = Int(configDict["socket.max.fails"] ?? "")
        self.brokerAddressTtl = Int(configDict["broker.address.ttl"] ?? "")
        self.brokerAddressFamily = .init(rawValue: configDict["broker.address.family"] ?? "")
        self.socketConnectionSetupTimeoutMs = Int(configDict["socket.connection.setup.timeout.ms"] ?? "")
        self.connectionsMaxIdleMs = Int(configDict["connections.max.idle.ms"] ?? "")
        self.reconnectBackoffMs = Int(configDict["reconnect.backoff.ms"] ?? "")
        self.reconnectBackoffMaxMs = Int(configDict["reconnect.backoff.max.ms"] ?? "")
        self.statisticsIntervalMs = Int(configDict["statistics.interval.ms"] ?? "")
        self.enabled_events = Int(configDict["enabled_events"] ?? "")
        self.log_level = Int(configDict["log_level"] ?? "")
        self.logQueue = Bool(configDict["log.queue"] ?? "")
        self.logThreadName = Bool(configDict["log.thread.name"] ?? "")
        self.enableRandomSeed = Bool(configDict["enable.random.seed"] ?? "")
        self.logConnectionClose = Bool(configDict["log.connection.close"] ?? "")
        self.internalTerminationSignal = Int(configDict["internal.termination.signal"] ?? "")
        self.apiVersionRequest = Bool(configDict["api.version.request"] ?? "")
        self.apiVersionRequestTimeoutMs = Int(configDict["api.version.request.timeout.ms"] ?? "")
        self.apiVersionFallbackMs = Int(configDict["api.version.fallback.ms"] ?? "")
        self.brokerVersionFallback = configDict["broker.version.fallback"]
        self.allowAutoCreateTopics = Bool(configDict["allow.auto.create.topics"] ?? "")
        self.securityProtocol = .init(rawValue: configDict["security.protocol"] ?? "")
        self.sslCipherSuites = configDict["ssl.cipher.suites"]
        self.sslCurvesList = configDict["ssl.curves.list"]
        self.sslSigalgsList = configDict["ssl.sigalgs.list"]
        self.sslKeyLocation = configDict["ssl.key.location"]
        self.sslKeyPassword = configDict["ssl.key.password"]
        self.sslKeyPem = configDict["ssl.key.pem"]
        self.sslCertificateLocation = configDict["ssl.certificate.location"]
        self.sslCertificatePem = configDict["ssl.certificate.pem"]
        self.sslCaLocation = configDict["ssl.ca.location"]
        self.sslCaPem = configDict["ssl.ca.pem"]
        self.sslCaCertificateStores = configDict["ssl.ca.certificate.stores"]
        self.sslCrlLocation = configDict["ssl.crl.location"]
        self.sslKeystoreLocation = configDict["ssl.keystore.location"]
        self.sslKeystorePassword = configDict["ssl.keystore.password"]
        self.sslProviders = configDict["ssl.providers"]
        self.sslEngineId = configDict["ssl.engine.id"]
        self.enableSslCertificateVerification = Bool(configDict["enable.ssl.certificate.verification"] ?? "")
        self.sslEndpointIdentificationAlgorithm = .init(rawValue: configDict["ssl.endpoint.identification.algorithm"] ?? "")
        self.saslMechanisms = configDict["sasl.mechanisms"]
        self.saslMechanism = configDict["sasl.mechanism"]
        self.saslKerberosServiceName = configDict["sasl.kerberos.service.name"]
        self.saslKerberosPrincipal = configDict["sasl.kerberos.principal"]
        self.saslKerberosKinitCmd = configDict["sasl.kerberos.kinit.cmd"]
        self.saslKerberosKeytab = configDict["sasl.kerberos.keytab"]
        self.saslKerberosMinTimeBeforeRelogin = Int(configDict["sasl.kerberos.min.time.before.relogin"] ?? "")
        self.saslUsername = configDict["sasl.username"]
        self.saslPassword = configDict["sasl.password"]
        self.saslOauthbearerConfig = configDict["sasl.oauthbearer.config"]
        self.enableSaslOauthbearerUnsecureJwt = Bool(configDict["enable.sasl.oauthbearer.unsecure.jwt"] ?? "")
        self.saslOauthbearerMethod = .init(rawValue: configDict["sasl.oauthbearer.method"] ?? "")
        self.saslOauthbearerClientId = configDict["sasl.oauthbearer.client.id"]
        self.saslOauthbearerClientSecret = configDict["sasl.oauthbearer.client.secret"]
        self.saslOauthbearerScope = configDict["sasl.oauthbearer.scope"]
        self.saslOauthbearerExtensions = configDict["sasl.oauthbearer.extensions"]
        self.saslOauthbearerTokenEndpointUrl = configDict["sasl.oauthbearer.token.endpoint.url"]
        self.pluginLibraryPaths = configDict["plugin.library.paths"]
        self.groupId = configDict["group.id"]
        self.groupInstanceId = configDict["group.instance.id"]
        self.partitionAssignmentStrategy = configDict["partition.assignment.strategy"]
        self.sessionTimeoutMs = Int(configDict["session.timeout.ms"] ?? "")
        self.heartbeatIntervalMs = Int(configDict["heartbeat.interval.ms"] ?? "")
        self.groupProtocolType = configDict["group.protocol.type"]
        self.groupProtocol = .init(rawValue: configDict["group.protocol"] ?? "")
        self.groupRemoteAssignor = configDict["group.remote.assignor"]
        self.coordinatorQueryIntervalMs = Int(configDict["coordinator.query.interval.ms"] ?? "")
        self.maxPollIntervalMs = Int(configDict["max.poll.interval.ms"] ?? "")
        self.enableAutoCommit = Bool(configDict["enable.auto.commit"] ?? "")
        self.autoCommitIntervalMs = Int(configDict["auto.commit.interval.ms"] ?? "")
        self.enableAutoOffsetStore = Bool(configDict["enable.auto.offset.store"] ?? "")
        self.queuedMinMessages = Int(configDict["queued.min.messages"] ?? "")
        self.queuedMaxMessagesKbytes = Int(configDict["queued.max.messages.kbytes"] ?? "")
        self.fetchWaitMaxMs = Int(configDict["fetch.wait.max.ms"] ?? "")
        self.fetchQueueBackoffMs = Int(configDict["fetch.queue.backoff.ms"] ?? "")
        self.fetchMessageMaxBytes = Int(configDict["fetch.message.max.bytes"] ?? "")
        self.maxPartitionFetchBytes = Int(configDict["max.partition.fetch.bytes"] ?? "")
        self.fetchMaxBytes = Int(configDict["fetch.max.bytes"] ?? "")
        self.fetchMinBytes = Int(configDict["fetch.min.bytes"] ?? "")
        self.fetchErrorBackoffMs = Int(configDict["fetch.error.backoff.ms"] ?? "")
        self.isolationLevel = .init(rawValue: configDict["isolation.level"] ?? "")
        self.enablePartitionEof = Bool(configDict["enable.partition.eof"] ?? "")
        self.checkCrcs = Bool(configDict["check.crcs"] ?? "")
        self.clientRack = configDict["client.rack"]
        self.retryBackoffMs = Int(configDict["retry.backoff.ms"] ?? "")
        self.retryBackoffMaxMs = Int(configDict["retry.backoff.max.ms"] ?? "")
        self.clientDnsLookup = .init(rawValue: configDict["client.dns.lookup"] ?? "")
        self.enableMetricsPush = Bool(configDict["enable.metrics.push"] ?? "")
        self.autoOffsetReset = .init(rawValue: configDict["auto.offset.reset"] ?? "")
        self.consumeCallbackMaxMessages = Int(configDict["consume.callback.max.messages"] ?? "")
    }
}
