version: "3"

services:

  runtime-setup:
    image: swift-kafka-client:22.04-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-jammy"

  build:
    image: swift-kafka-client:22.04-5.10

  test:
    image: swift-kafka-client:22.04-5.10
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-kafka-client:22.04-5.10
