name: swift-kafka-client

services:
  kafka:
    image: apache/kafka:3.9.1
    healthcheck:
      test:
        [
          "CMD",
          "kafka-broker-api-versions.sh",
          "--bootstrap-server=localhost:9092",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  client:
    image: swift-kafka-client:${IMAGE_TAG:-local-${SWIFT_VERSION:-6.0}-${UBUNTU_VERSION:-jammy}-${IMAGE_PLATFORM:-amd64}}
    build:
      args:
        ubuntu_version: "${UBUNTU_VERSION:-jammy}"
        swift_version: "${SWIFT_VERSION:-6.0}"
      platforms:
        - linux/${IMAGE_PLATFORM:-amd64}
    depends_on: [kafka]
    volumes:
      - ..:/swift-kafka-client:z
    working_dir: /swift-kafka-client
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    command: ["/bin/bash"]
